### ISSUE TITLE
Merge repositories

### ISSUE THREAD

**Issue by alvaro-octal** [hakimio/ngx-ui-tour#1]
Hi,

@krmarien and me have been working on keeping ngx-tour up to date, and adding some things like automatic releases, specific git submodules etc., would you agree on joining efforts arround https://github.com/ngx-tour/ngx-tour ([@ngx-tour/core](https://www.npmjs.com/package/@ngx-tour/core))?

**Comment by hakimio** [comment]
Hi Alvaro,

I took a quick look at your fork. There are some nice changes you've made:
- Demo/documentation page looks good.
- New way to organize npm packages is a good idea.
- Changes to backdrop service. Configurable zIndex is nice. Also, changing position from "fixed" to "absolute" might theoretically be a good idea, but it's just a simple work-around/band-aid for the demo page. Proper solution would be to find a way to disable main page scrolling (allowing scrolling inside tour step) when UI tour is active without using any 3rd party libraries.
- Automatic releases is a good idea but for such a small project, I don't think they are a must have. I think it would be a lot more helpful if someone made proper unit tests which would have to pass before merging PRs.

There are also few things I am not a fan of:
- I don't like splitting the project into multiple repositories. Imho, Nrwl Nx monorepo makes it easier to manage/contribute to the project.
- I am not sure why you made [this change](https://github.com/ngx-tour/ngx-tour-md-menu/commit/b30ddd86fafc82858a63150ba2f4aaa2d1ba0cc2). I have added that if statement to avoid backdrop flickering when switching from one step to another. If the next step is not supposed to have a backdrop, it's removed in `showTourStep()` method.
- README. First impression matters and in it's current state the main README and submodule READMEs don't offer much/any value plus often failing to load dependency badges look pretty ugly.

Anyway, I like having full control of this project and being able to release new packages without having to wait for someone to do it in a 3rd party project. I am pretty happy with the current state of this project and I don't see any reason why I would want to switch to the one you maintain.
If you would like to contribute to this project, feel free to create new PRs here and I'll try to review them ASAP.
