### ISSUE TITLE
I want step route to not ignore fragment

### ISSUE THREAD

**Issue by mivanyna** [hakimio/ngx-ui-tour#100]
I have different steps on different tabs, which is connected to route fragment.
Now, user have to click on tab to go to next step and there is no possibility to switch back using Prev step button(except in code, but we still don't have direction property exposed)

Is there a reason why fragment is ignored in route?

![image](https://user-images.githubusercontent.com/10868397/210532344-a2f8a18e-bfb6-4300-aa06-258afd7b8956.png)

**Comment by mivanyna** [comment]
Or maybe we can have an option `routeFragmentMatch: 'ignored'` by default and user can override it for each step?

**Comment by mivanyna** [comment]
@hakimio please check and maybe advice better description for the option https://github.com/hakimio/ngx-ui-tour/pull/101

**Comment by hakimio** [comment]
Fragment is no longer ignored  in `v10`.
