### ISSUE TITLE
[Bootstrap] Include step title in tour step template

### ISSUE THREAD

**Issue by rmoncler-ctl** [hakimio/ngx-ui-tour#102]
Hi,

I installed ngx-ui-tour-ngx-bootstrap for testing it with an existing app.
I am currently testing the custom template part, but I met a problem I cannot seem to solve :

- The example from the online documentation (https://hakimio.github.io/ngx-ui-tour/ngx-bootstrap/Misc#custom-template) only starts with the "content" part of the template, the "title" part is not included.
- While the README.md file found in the node_module folder shows the customization of the title property as follow :
![image](https://user-images.githubusercontent.com/95758743/214817338-d9d524a6-4062-47c5-9b29-90f4bb9a810d.png)

Obviously, this does not work with my version (using ngx-bootstrap, I guess this "mat-card-title" is related to the usage of Material Design).

Is there a way to customize the title part of the template when using ngx-ui-tour-ngx-bootstrap ? Or is it possible only for projects that use MD ?

Also, I'm currently using Angular 9 and ngx-ui-tour 7.0.2

**Comment by hakimio** [comment]
When using `NG Bootstrap` and `Ngx Bootstrap` UI implementations, the title is part of the popover and can only be customized using CSS class `h3.popover-header`. 
You have more freedom when using other UI implementations like "Angular Material", "Ionic" or "Taiga UI". 
Next major release will include revamped Bootstrap default template and it will be possible to customize the title in custom template but the release is not coming anytime soon.

**Comment by hakimio** [comment]
You customize the title style in `v11`. Check out [the release announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v11.0.0).
