### ISSUE TITLE
🐞 - isAsync is not working as expected

### ISSUE THREAD

**Issue by rmoncler-ctl** [hakimio/ngx-ui-tour#105]
### Which ngx-ui-tour-* package is the source of the bug?

ngx-bootstrap

### Description

Hi,

I'm having an issue when I add a `tourAnchor` on an element that is displayed only after getting the result of an HTTP request.

For the first few steps (on elements that are present on the page without having to wait for a request response), no problem.
But when I do `next()` in order to show the step related to this async element, the backdrop stays on the previous step, the previous popup disappears and no new popup appears.

I tried adding `isAsync: true` to this step, but it almost does not change anything (only the "`Can't attach to unregistered anchor with id XXX`" error is not displayed anymore).
I also tried adding delayAfterNavigation, but it does no seem to change anything either.

This is a problem I have on every route/page containing data displayed based on the result of an HTTP request : adding a tour step on any element displayed asynchronously results in an "empty step" when running the tour.

Do I miss something obvious here? Or could this be related to the version of `ngx-ui-tour` I use?

### Angular version

9.1.15

### Ngx UI Tour version

7.0.2

### Which browsers have you used?

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [x] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
Making the step `async` should solve your issue.
- Did you import `TourNgxBootstrapModule` in the module where you added your missing `tourAnchor`?
- Did you import `TourNgxBootstrapModule.forRoot()` in your app module?
- Is the `tourAnchor` on the html element spelled exactly the same like the `anchorId` in step definition?
- Can you see if the `tourAnchor` is registered after your data is loaded by listening to `anchorUnregister$` [event](https://hakimio.github.io/ngx-ui-tour/ngx-bootstrap/API#events)?

**Comment by rmoncler-ctl** [comment]
Oh no...
I had a typo in the anchorId.
So now it works...
Thanks!

**Comment by hakimio** [comment]
Awesome :)
