### ISSUE TITLE
Error handling when a tourAnchor does not exist 🚀 - 

### ISSUE THREAD

**Issue by Snookmz** [hakimio/ngx-ui-tour#109]
### Which ngx-ui-tour-* package is relevant to the feature request?

ionic

### Description

In Ionic/Angular (but possibly relevant for other frameworks) when we try and attach to an unregistered tourAnchor when a tour is already started we get into a 'stuck' state.

i.e. If we are part way through a tour and the next step refers to a tourAnchor that does not exist then the tour gets into a 'stuck' state with the backdrop and the last highlighted tourAnchor still active, but no buttons to dismiss. Clicking on the backdrop directly also does not dismiss the tour. The user becomes 'stuck' and cannot do anything. A user needs to refresh the app in the browser to get 'unstuck', and this probably wouldn't work when on a iOS / Android device.

**Request**: Can we handle this broken state better? 

**Suggestions**: 
- Do not let the tour start if there's a tourAnchor that Tour Service cannot find.
- Allow a user to dismiss the tour by clicking on the background (in a similar way that ionic modals can be dismissed).

**Comment by hakimio** [comment]
You already have a couple of ways to deal with missing anchors:
- If the step should be skipped when anchor element is missing, set the step as `optional`
- If the tour should wait for the anchor to be added to DOM, set it as `async`

Anyway, what's the reason for the missing tour anchor in your case?

**Comment by Snookmz** [comment]
I apologise for missing these options. There are various reasons that anchors can be missing, given the dynamic nature of SPAs sometimes anchors are not displayed. I've mostly worked around this by sending flags to a function that sets the steps according to the current state of the app. But sometimes I miss a condition which caused the 'hung' state in the tour I explained in my 'issue'.

I'll try those options you have suggested. But in my mind it would make more sense to throw an error and exit the tour if an anchor is not found as opposed to leave it in the 'hung' state.

**Comment by hakimio** [comment]
Yes, it logs an error to JS console and [ends the tour](https://github.com/hakimio/ngx-ui-tour/blob/6356be87bea7b1754a08ce90e132e41a0ff83d59/projects/ngx-ui-tour-core/src/lib/tour.service.ts#L453) when tour anchor is not found.
Here is the demo: https://stackblitz.com/edit/angular-wau2z8-kvlzpe?file=src%2Fapp%2Fui-tour-demo.component.ts

If it doesn't work like that for you, please create a separate issue with a reproduction.

**Comment by Snookmz** [comment]
I can see it behaves correctly from your stackblitz. Could be because I'm running an older version '8.1.2' as I'm running Angular 12. 

I appreciate the quick response and all your work, love the library.

**Comment by hakimio** [comment]
Thanks :)

**Comment by hakimio** [comment]
Remember to star the library, if you like it.
