### ISSUE TITLE
🐞 - Popover not visible on android with custom template

### ISSUE THREAD

**Issue by ludonoel1** [hakimio/ngx-ui-tour#114]
### Which ngx-ui-tour-* package is the source of the bug?

ionic

### Please provide a link to a minimal reproduction of the bug

https://ionic6-angular13-fybot1.stackblitz.io

### Description

I use a custom-template and it's workign on ios but not on Android..
It seems that popover is behind everything...

### Angular version

15.2.2

### Ngx UI Tour version

1.4.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by ludonoel1** [comment]
I would like to center my popover on my screen , that's why I set position: fixed.

However with position: relative I see my popover but impossible to center it.

By the way is there any way to change width of popover with css ?

Thanks

**Comment by hakimio** [comment]
Have you read FAQ: https://hakimio.github.io/ngx-ui-tour/ion-popover/FAQ#center-tour-step ?

**Comment by ludonoel1** [comment]
Yes and that changed style of my div... and dont want that

**Comment by hakimio** [comment]
How can fixed 0px width and height div change anything in your app?
Anyway, it seems to work fine in this demo: https://stackblitz.com/edit/ionic6-angular13-rypta7?file=src%2Fapp%2Fapp.component.css

**Comment by hakimio** [comment]
I tested on my Android phone with custom template and can not reproduce the issue. The step is shown correctly for me.
I'll make it possible to customize tour step width with CSS variable in the next minor release.

**Comment by hakimio** [comment]
@ludonoel1 I have released a new version where you can customize tour step width. Check out [the release announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v10.5.0) for more info.
