### ISSUE TITLE
🚀 -  Hide arrow in config

### ISSUE THREAD

**Issue by ludonoel1** [hakimio/ngx-ui-tour#115]
### Which ngx-ui-tour-* package is relevant to the feature request?

ionic

### Description

I'm using ionic lib and I would like to hide arrow but is there any way to do it by config ?

Thanks

**Comment by hakimio** [comment]
Not yet, but I can add the config.

**Comment by ludonoel1** [comment]
Yes please it could be wonderful

**Comment by ludonoel1** [comment]
Any news ? Or date for future release please

**Comment by hakimio** [comment]
Most likely I will release a new version next week. I am quite busy at the moment.

**Comment by hakimio** [comment]
Released [new version](https://github.com/hakimio/ngx-ui-tour/releases/tag/v10.6.0). Let me know if it works as expected.
