### ISSUE TITLE
🚀 - Provide default tour settings without specifying tour steps

### ISSUE THREAD

**Issue by mivanyna** [hakimio/ngx-ui-tour#117]
### Which ngx-ui-tour-* package is the source of the bug?

ng-bootstrap

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wau2z8?file=src%2Fapp%2Fui-tour-demo.component.ts

### Description

Getting an error `ERROR Error: Tour anchor with id "some-id" already registered!` even the tour hasn't started yet.

Configuration of the tour hasn't been applied yet, seems we need to have some default global settings to be applied even before tour is started.

A similar issue might occur when the user started the tour and has set `allowUserInitiatedNavigation: true` and `isAsync: true` for first step and navigation(or route update) happens before the first step is shown.

### Angular version

15

### Ngx UI Tour version

12.5.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
The error has nothing to do with tour starting. If you want to use duplicate tour anchors, you have to set duplicateAnchorHandling option.

**Comment by mivanyna** [comment]
Yeah, but I have few tours and steps isn't initialized yet as I don't know which one user will start

**Comment by hakimio** [comment]
What would you suggest to do about it?

**Comment by mivanyna** [comment]
I suggest adding some kind of default options that users will be able to set on the app start and fallback if there is not step to those default options.

**Comment by hakimio** [comment]
Maybe providing default settings with a DI token could be a solution for this.

**Comment by hakimio** [comment]
You can now set `duplicateAnchorHandling` option without setting the tour steps.
```ts
this.tourService.setDefaults({
    duplicateAnchorHandling: 'registerFirst'
});
```
Let me know if it fixes your error.

**Comment by mivanyna** [comment]
Hi, have checked, it works, thanks!
