### ISSUE TITLE
🚀 - Show step next to anchor instead of only above/below

### ISSUE THREAD

**Issue by kpaxton** [hakimio/ngx-ui-tour#122]
### Which ngx-ui-tour-* package is relevant to the feature request?

md-menu

### Description

I'd love to be able to display a step to the left or right of the anchor. 

This project has done it with the material menu component as well. https://github.com/Broadcom/bdc-walkthrough

**Comment by hakimio** [comment]
All [`mat-menu` positioning options](https://material.angular.io/components/menu/api#:~:text=%40Input()-,xPosition%3A%20MenuPositionX,-Position%20of%20the) are already supported by the library. If it doesn't appear where you want after using those options, most likely the issue is that there isn't enough space.

**Comment by kpaxton** [comment]
Not willing to expand upon the positioning options to provide more? Mat Menu does have the ability to display to the side, it's just primarily used for sub-menu's.

**Comment by hakimio** [comment]
What positioning option is missing? You can already control both horizontal and vertical position of the tour step.

**Comment by kpaxton** [comment]
The out of the box menu positioning options are not missing. However, it could be expanded upon as the bdc-walkthrough library has done. They added a `horizontal` option on the step to allow for the menu to be displayed to the side of the anchor instead of above/below. 

I initially started trying to use bdc-walkthrough, but it did not fit in with my codebase and how I wanted to use it. Your's is much better for integrating the tours into my state management and making it more flexible programatically. I just also have the requirement to allow for displaying it to the side (before/after) instead of above/below.

Some of the code looks to be replicated from the mat-menu source...
bdc-walkthrough: https://github.com/Broadcom/bdc-walkthrough/blob/master/projects/bdc-walkthrough/src/lib/tutorial-popup/tutorial-trigger.directive.ts
mat-menu: https://github.com/angular/components/blob/main/src/material/menu/menu-trigger.ts

**Comment by hakimio** [comment]
Ok, sorry. I understand now what you mean.
Anyway, I don't personally plan to implement this functionality but if you are willing to create a PR with simplified version of what `bdc-walkthrough` does, I can take a look at it.
The issue I see is that the custom positioning adds a lot of code to the `md-menu` implementation and I like to keep tour UIs as simple as possible.

**Comment by kpaxton** [comment]
Ok, thanks. I'll try to take a look if I have time. 

Out of curiosity, any particular reason the tour is based off of matMenu vs matTooltip which has more positioning options?

**Comment by hakimio** [comment]
No, no particular reason. The decision was made by @isaacplmann in his `ngx-tour`. `ngx-ui-tour` is just a fork of that library.
I am ok with adding `matTooltip` version of the UI, if you are willing to do the work.

**Comment by kpaxton** [comment]
BTW thank you for responding so quickly!
