### ISSUE TITLE
🐞 - Tour Step dissapears when hovering over matMenu

### ISSUE THREAD

**Issue by kpaxton** [hakimio/ngx-ui-tour#123]
### Which ngx-ui-tour-* package is the source of the bug?

md-menu

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wau2z8-qtokex?file=src/app/ui-tour-demo.component.html

### Description

When highlighting an item that is displayed as part of a menu the tour will prematurely disappear if you hover over any of the other menu items while the tour is open. As far as I can tell, I can't get it back either. 

* Click button to open menu.
* menu shows and tour step shows.
* Hover over menu item
* Tour disappears and does not show next steps and can't recover.

see stackblitz: https://stackblitz.com/edit/angular-wau2z8-qtokex?file=src%2Fapp%2Fui-tour-demo.component.html

### Angular version

15.2.8

### Ngx UI Tour version

10.6.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
As a workaround you can set `closeOnOutsideClick: true`.

**Comment by kpaxton** [comment]
yes, I saw that option. It does not seem to fix this case. There is no click that is closing it, it's on hover.

**Comment by hakimio** [comment]
Did you set it to `true` or `false`? Seems to work for me: https://stackblitz.com/edit/angular-wau2z8-tmjjrs?file=src%2Fapp%2Fui-tour-demo.component.ts

**Comment by kpaxton** [comment]
Ah, nope. I set it to false because I didn't want it to close when clicking outside of it. True does seem to eliminate it disappearing on hover, but I'd still like it to only close when clicking an appropriate action inside the step.

**Comment by hakimio** [comment]
Fixed in [v10.7.0](https://github.com/hakimio/ngx-ui-tour/releases/tag/md-menu%40v10.7.0).
Let me know if it works for you.
