### ISSUE TITLE
🚀 - Add an option to for `force` within the tourService.end() method.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [hakimio/ngx-ui-tour#126]
### Which ngx-ui-tour-* package is relevant to the feature request?

ionic

### Description

I have a service configured with a subscription attached to the $end Observable like so.

```
async startTour(key: string, callback: Function = null) {
		let searchTourItem = this.tourItems.find(t => t.key === key)
		let version = await Preferences.get({ key: key })
		if (!version.value || version.value !== searchTourItem.version) {
			this.tourService.initialize(searchTourItem.steps, searchTourItem.settings);
			this.tourService
				.end$
				.pipe(take(1))
				.subscribe(async () => {
					await this.markTourComplete(key)
					if (callback) {
						callback('complete')
					}

				});
			this.tourService.start()
		} else if (callback) {
			callback('complete')
		}
	}
```

In certain scenarios I would like to end the tour abruptly, so I'm calling `tourService.end()`  I've noticed that the $end observable is still triggered in this scenario though. It would be nice to be able to pass a flag like `tourService.end({force:true})` which would prevent any events from firing. 

I understand I can implement this in my wrapper service, but it would be a nice option to have when ending a tour.

**Comment by hakimio** [comment]
Sorry, but I don't think it's a good addition for the library. The current behavior makes perfect sense.
If you need some special handling of abrupt tour end, just add a property `tourAbruptEnd` to your service and then check the property in your `end$` subscription.
