### ISSUE TITLE
🚀 - Support Angular 16

### ISSUE THREAD

**Issue by kpaxton** [hakimio/ngx-ui-tour#129]
### Which ngx-ui-tour-* package is the source of the bug?

md-menu

### Description

I'm sure you're probably already working this, but just to record it.

`npm install` comes back with a conflicting peer dependency error requiring material and cdk at ^15.0.0. 

``` 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: ngx-ui-tour-md-menu@10.7.0
npm ERR! Found: @angular/cdk@16.0.2
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"16.0.2" from the root project
npm ERR!   peer @angular/cdk@"16.0.2" from @angular/material@16.0.2
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"16.0.2" from the root project
npm ERR!   1 more (ng2-charts)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^15.0.0" from ngx-ui-tour-md-menu@10.7.0
npm ERR! node_modules/ngx-ui-tour-md-menu
npm ERR!   ngx-ui-tour-md-menu@"^10.7.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/cdk@15.2.9
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"^15.0.0" from ngx-ui-tour-md-menu@10.7.0
npm ERR!   node_modules/ngx-ui-tour-md-menu
npm ERR!     ngx-ui-tour-md-menu@"^10.7.0" from the root project
```

### Angular version

16

### Ngx UI Tour version

10.7.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by andriilazebnyi** [comment]
@hakimio Are there any ETAs when NG 16 support would be added? Thank you 🙏

**Comment by hakimio** [comment]
In addition to ng 16 update, I am planning to add few new features to the upcoming v11 release.
Depending how it goes with those features and how much time I have, I expect to push the update this or next week.

**Comment by hakimio** [comment]
v11 has been released. Check out [the release announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v11.0.0).
