### ISSUE TITLE
🐞 - [v9] incorrect scroll position when going to previous step

### ISSUE THREAD

**Issue by tansukhkumar** [hakimio/ngx-ui-tour#135]
### Which ngx-ui-tour-* package is the source of the bug?

md-menu

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wau2z8?file=src%2Fapp%2Fui-tour-demo.component.ts

### Description

Hi 
on click of previous button, the screen does not get scrolled up correctly to highlight the current tour anchor_id. 

please refer to the attachments.

using "ngx-ui-tour-md-menu": "^9.3.1"

![Screenshot 2023-07-31 at 5 39 11 PM](https://github.com/hakimio/ngx-ui-tour/assets/59333986/431c92ad-7b9c-416b-a76f-4b0183c3b354)

https://github.com/hakimio/ngx-ui-tour/assets/59333986/03222e52-28db-4df0-9dbd-332192939dc4

### Angular version

14.2.12

### Ngx UI Tour version

9.3.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by tansukhkumar** [comment]
once scroll down while clicking next tour anchor button. it does not properly go up to show tour anchor element when clicked on previous button.

**Comment by hakimio** [comment]
Please provide Stackblitz reproduction using the latest version of the library. I don't support old library versions.

**Comment by tansukhkumar** [comment]
hi
thanks for reply. I handle it on my side.

**Comment by hakimio** [comment]
Would be interesting to know how you handled it.
