### ISSUE TITLE
🚀 - Additional parameter for hideTourStep to indicate if the next or previous step is already available.

### ISSUE THREAD

**Issue by SebastianStehle** [hakimio/ngx-ui-tour#137]
### Which ngx-ui-tour-* package is relevant to the feature request?

console

### Description

Hi,

I am using ngx-ui-tour-core, so it matches better to this package. I would like to animate the step modal when you move to the next step. But hideTourStep() is always called, even when the next step is already available. Therefore it destroys the element and then recreates it.

I have a few workarounds in mind, e.g. I could maintain a flag that is called, when prev() or next() is clicked and prevents the call basically, but it is a little bit ugly and the next step could also be triggered when nextOnAnchorClick is set to true. Therefore I would like to have a flag that indicates the reason, why hideTourStep() is invoked.

**Comment by hakimio** [comment]
Sorry, I don't really understand what's the issue. `hideTourStep()` is called on the step that should appear next?
Can you list how it works now and how you think it's supposed to work?

**Comment by SebastianStehle** [comment]
Lets say we have a tour with 2 steps (Step A and B) and 2 directives (DirectiveA, DirectiveB).

The user goes through the tour, then the flow is as followed:

1. directive**A**.showTourStep(step**A**); => Create modal
2. directive**A**.hideTourStep(); => Destroy modal
3. directive**B**.showTourStep(step**B**); => Create modal
4. directive**B**.hideTourStep(); => Destroy modal

Ideally we would have a reason why hideTourStep is called:

1. directive**A**.showTourStep(step**A**); => Create modal
2. directive**A**.hideTourStep(reason: 'NextReadyStep'); => Do nothing
3. directive**B**.showTourStep(step**B**); => Reposition modal
4. directive**B**.hideTourStep(reason: 'Finished'); => Destroy modal

A reason could be:

* Closed
* Finished
* NextReadyStep
* NextPendingStep (Either awaiting route or delayed or so)

EDIT: I have solved it myself while writing that, sorry. The trick was easy. I just hide the element immediately and delay the destroy for a few seconds (and cancel that when showTourStep is called again).

**Comment by hakimio** [comment]
Instead of `setTimeout()` hack, you can just check tour state in your hide tour step handler: `this.tourService.getStatus() === TourState.OFF`. If the state is `OFF`, you can safely destroy your modal.

**Comment by SebastianStehle** [comment]
I will try that. Thank you.

**Comment by hakimio** [comment]
Did `getStatus()` help in your case?

**Comment by hakimio** [comment]
Closing since there are no plans to implement this at this point.
