### ISSUE TITLE
🐞 - Backdrop is not positioned properly when developer console is opened

### ISSUE THREAD

**Issue by SebastianStehle** [hakimio/ngx-ui-tour#138]
### Which ngx-ui-tour-* package is the source of the bug?

md-menu

### Description

I don't know why it does not happen with the demo, but for me the backdrop is sometimes not updated.

This is especially the case, when the developer tools are enabled or disabled. The reason seems to be that the resize listener does not trigger then. I added a breakpoint to the `setBackdropPosition` method and it was not triggered.

I had similar problems and the only reliable fix for me was actually a timer.

![image](https://github.com/hakimio/ngx-ui-tour/assets/1236435/c5e90e2c-fc20-45be-aa43-572bc72e8ade)

### Angular version

116.

### Ngx UI Tour version

11.0.3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
Does this ever happen when dev tools are not open? 
Anyway, you can try to set `delayBeforeStepShow` to see if that helps.

**Comment by SebastianStehle** [comment]
It happens while I am on a step and the backdrop is always visible. When I then turn on developer console, the backdrop is not updated. If I resize the window normally it gets updated.

**Comment by hakimio** [comment]
- Does this happen when developer console is not open? Yes or No?
- Have you tried `delayBeforeStepShow` to see if it helps?
- Does this happen when using smooth scroll feature?
- Can you reproduce the issue on Stackblitz without dev console: https://stackblitz.com/edit/angular-wau2z8 ?

**Comment by SebastianStehle** [comment]
I think you get me wrong. The flow is as followed:

* You go to a step, then the backdrop renders properly
* If you then open the developer console, the backdrop is not repositioned, because the resize event is not triggered.
* Therefore scolling and delayBeforeStepShow has no impact.

**Comment by hakimio** [comment]
If it's caused only by opening dev console, I don't think that's an issue for normal users.
If you manage to consistently reproduce the issue without dev console open/close, feel free to submit a new issue.

**Comment by SebastianStehle** [comment]
I can reproduce it here: https://stackblitz.com/edit/angular-wau2z8-lbkisp?file=src%2Fstyles.scss

You need a scroll container for that. It also happens when I resize the window with Window + Arrow keys.

**Comment by hakimio** [comment]
That's not a bug with the library. When you are using custom scroll container, you have to specify it using `scrollContainer` config: `scrollContainer: '.container'`. Then everything works fine.
Anyway, feel free to open new issue to improve the docs.

**Comment by hakimio** [comment]
Ok, another issue with your demo is that you have two main content scroll containers (`.container` and `html`). Normally you would have only one.

**Comment by hakimio** [comment]
Here is your reproduction fixed and working as intended: https://stackblitz.com/edit/angular-wau2z8-towkfa

**Comment by SebastianStehle** [comment]
Thanks. I found the same solution. I think I would probably set the html and body to `overflow: hidden` dynamically, because I cannot foresee what could actually break, if I change that, but this seems to work.
