### ISSUE TITLE
🚀 - Tour should be cancelled when the target element is destroyed.

### ISSUE THREAD

**Issue by SebastianStehle** [hakimio/ngx-ui-tour#139]
### Which ngx-ui-tour-* package is relevant to the feature request?

Don't known / other

### Description

When a directive calls unregister, only the anchor is removed.

But if the directive represents the active step, the modal has no target element anymore and should actually be destroyed. Lets say your target element is a dialog and the dialog is closed while it is the current step. This actually ends the tour, but the backdrop remains.

e.g something like this:
```
public unregister(anchorId: string): void {
        if (!anchorId) {
            return;
        }
        delete this.anchors[anchorId];
        this.anchorUnregister$.next(anchorId);

        if (this.currentStep?.stepId === anchorId) {
           this.end();
        }
    }
```

I have solved it in my own TourAnchorDirective, but perhaps it should be a general feature.

**Comment by hakimio** [comment]
I don't think that's a good idea, since it would break multi-route tours where anchors get unregistered when going to a different route.

**Comment by SebastianStehle** [comment]
You just have to set the currentStep to null, before changing URL.

**Comment by hakimio** [comment]
I don't get how that fixes anything.
Anyway, if it's a big issue for you, feel free to submit a PR.
For me it seems like an issue is specific to your tour and doesn't affect many users.

**Comment by SebastianStehle** [comment]
You are right, it is really tricky.

My tour and use case is the following:

1. User clicks a button
2. A dialog is opened with the option to create an element and to cancel. Both actions close the element.
3. The tour resumes automatically when the element is created.

I added a special property to wait for the next element: `nextOnCondition`, e.g. it looks like this:

```
{
   anchorId: 'fieldForm',
   content: 'i18n:tour.createSchema.fieldFormContent',
   nextOnCondition: waitForAnchor('schemaField'),
}, {
   anchorId: 'schemaField',
   content: 'i18n:tour.createSchema.schemaFieldContent',
}, 
```

If the nextOnCondition becomes true, it continues with the tour.

The problem is that I cannot really distinguish between Close and Save. Therefore my only solution is to wait a few milliseconds in the onDestroy event and then pause the tour. The delay is needed to avoid flickering effect, because the backdrop is closed and reopened in a few milliseconds. I wish I would have a better solution for that.

**Comment by hakimio** [comment]
There is no need to reinvent the wheel. You can just mark the step with "schemaField" anchor id as `async` (`isAsync` option) and the tour will automatically wait for it.

**Comment by SebastianStehle** [comment]
It is not the same:

1. It works as a trigger, similar to nextOnAnchorClick
2. It waits for new anchors, so that we focus the newly created element (should be named `waitForNewAnchor`).

But the same problem happens with "isAsync". if the current element is destroyed and the new element is not created yet, you don't know what's going on.

Btw: Perhaps the isAsync also needs a timeout, so that you are not stuck in the tour forever (e.g. when you have a backdrop).

**Comment by hakimio** [comment]
Maybe combination of `nextOnClick` and `isAsync` would work in your case. What triggers the dialog to popup?

> Perhaps the isAsync also needs a timeout

Not sure about that. Anchor element not showing up in this case indicates an issue with your application and introducing timeout would require a new setting plus the timeout would potentially break existing tours where the waiting time would be higher than the default setting.

**Comment by hakimio** [comment]
If you think some of the changes you made to your tour might benefit other users, feel free to create a PR.

**Comment by hakimio** [comment]
I will add `asyncStepTimeout` setting sometime soon, but I don't think cancelling the tour when the target element is destroyed is a good idea.
I have created a new feature request for `asyncStepTimeout` setting: #148
