### ISSUE TITLE
🐞 - `currentStep` is undefined after calling `tourService.start()`

### ISSUE THREAD

**Issue by ChrTall** [hakimio/ngx-ui-tour#145]
### Which ngx-ui-tour-* package is the source of the bug?

md-menu

### Description

With the recent updates I discovered a regression in my app.
The tourService.currentStep is undefined after I initialized the tour and started it.
After restarting the tour, current step is defined and can be used again.

### Angular version

16.2.2

### Ngx UI Tour version

11.0.3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
`currentStep` was always set asynchronously. You can't expect it to be set immediately after calling `start()`. This is not a bug.
You have to listen to `stepShow$` event or, as a less reliable solution, you could use `setTimeout()` to get the `currentStep`.

**Comment by ChrTall** [comment]
I added a variable currentStepId to my service and subscribed to tourService.stepShow$ to set it.
But I still have the same problem. Only after restarting the tour I can get the value.
My interactive steps emit an event when the action is done which contains the stepId of the action.
If the current step is equal to the events action the tour is progressing.
This worked flawlessly in previous versions.

**Comment by hakimio** [comment]
Maybe you accessing your `currentStepId` before your `stepShow$` handler sets it?
Create a reproduction of your issue if you want me to look at it.
Not sure how it could have reliably worked before when `currentStep` was always set asynchronously.

**Comment by hakimio** [comment]
Where did you find `currentStep` in the docs? I don't think it's documented anywhere.

**Comment by ChrTall** [comment]
Okay then I was wrong about that. Though it is a bit confusing that currentStep can be undefined.
