### ISSUE TITLE
🚀 - Replace centerAnchorOnScroll by postitionAnchorOnScroll

### ISSUE THREAD

**Issue by EliotRagueneau** [hakimio/ngx-ui-tour#153]
### Which ngx-ui-tour-* package is relevant to the feature request?

md-menu

### Description

It would be great if we could easily set the preferred position to scroll anchor to, rather than "end" by default and "center" as the only option possible.

The property could be like 
```ts
export type ScrollPosition = 'start' | 'center' | 'end' ;

export interface IMdStepOption {
  postitionAnchorOnScroll: ScrollPosition;
  ...
}
``` 

As of today, it looks like the order of priority is center > end > start:
https://github.com/hakimio/ngx-ui-tour/blob/3ba843ef4eba9d3a1ca6af121ff4fb560a3b7115/projects/ngx-ui-tour-core/src/lib/scrolling.service.ts#L30-L48
But sometimes you might want to scroll to start rather than to center or to end

**Comment by hakimio** [comment]
> As of today, it looks like the order of priority is center > end > start

It's not a simple "priority" and ordering the alignment preference like you did is just wrong.
It determines the alignment based on where the target element is in terms of the viewport and which parts of the element are obstructed. If it's above the viewport, it will align the top of the element, if it's below, it will align the bottom. Same logic based on which parts of the target element are covered by another element: if it's top, aligns top, if it's bottom, aligns the bottom of the element.
It tries to always center the element when `centerAnchorOnScroll` is enabled. This option is enabled by default in the latest version of the library.

I don't see any value of setting fixed top/bottom alignment position apart from your very specific case where you have anchor element which exceeds its scroll container's height.

**Comment by EliotRagueneau** [comment]
I get your point. it is indeed creating undesired behaviour in the specific case where the element is bigger than its scrollContainer.

I also get your point that this is not a very common situation, though I would argue that if an element is in a scrollContainer, it's because there are too many elements to fit inside a container, hence the scroll. Therefore, unless the scrollContainer is populated by many little elements, it's not so unlikely that some elements are bigger than the scroll container.

In any case, you are absolutely right about the "order" of priority, I didn't fully understood your ScrollService, thank you for your explanations, it's really enlightening.

I will therefore close this ticket as it is indeed void.

For my specific case, and if somebody else is also facing the same issues. I came up with the following dirty hack to only scroll to the top element.

@hakimio as you will notice, this hack is straight up copy paste from bits of your own code. I hope you don't mind.
This hack is indeed dirty since it duplicates code present in the library but not publicly available. Also this doesn't take into consideration `isAsync` steps, and is just for the next button right now, but it can "easily" be extended to cover those cases.

```html 
<tour-step-template>
  <ng-template let-step="step">
    <mat-card (click)="$event.stopPropagation()" ...>
      ...
        <button class="next" *ngIf="tourService.hasNext(step) && !step.nextOnAnchorClick"
                (click)="next()" mat-button>
          {{step.nextBtnTitle}}
          <mat-icon iconPositionEnd>chevron_right</mat-icon>
        </button>  
      ...
    </mat-card>
  </ng-template>
</tour-step-template>
```
```ts
@Component({
  selector: 'my-tour',
  templateUrl: './tour.component.html',
  styleUrls: ['./tour.component.scss']
})
export class TourComponent {
  constructor(public tourService: TourService) {
    this.tourService.setDefaults({
      centerAnchorOnScroll: false,
      disablePageScrolling: true,
      disableScrollToAnchor: true,
    });
  ...
  }

  async next() {
    const currentStep = this.tourService.currentStep;
    const nextStep = this.tourService.steps[this.tourService.steps.indexOf(currentStep) + 1];
    const elt = this.tourService.anchors[nextStep.anchorId as string].element.nativeElement;
    elt?.scrollIntoView({
      block: "start",
      behavior: "smooth",
      inline: "nearest"
    });
    await firstValueFrom(this.waitForScrollFinish$(nextStep));
    this.tour.next()
  }

  private waitForScrollFinish$(step: IMdStepOption) {
    const userScrollContainer = step.scrollContainer,
      scrollContainer = this.getScrollContainer(userScrollContainer) ?? document;

    return fromEvent(scrollContainer, 'scroll')
      .pipe(
        timeout({
          each: 75,
          with: () => of(undefined)
        }),
        debounceTime(50),
        map(() => undefined)
      );
  }

  getScrollContainer(userScrollContainer: string | HTMLElement | undefined): Element | null {
    if (typeof userScrollContainer === 'string') {
      return document.documentElement.querySelector(userScrollContainer);
    }
    if (userScrollContainer instanceof HTMLElement) {
      return userScrollContainer;
    }

    return null;
  }
}
```


I wanted to thank you @hakimio for having taken the time to reply to my issues, and sorry for having waisted your time on this one. 
This library is really great and have eased a lot my work 😄 

Best regards,
Eliot

**Comment by hakimio** [comment]
You are welcome and feel free to use the source code as you wish since the library is using permissive MIT license 🙂
