### ISSUE TITLE
Issue while implementing  ngx-ui-tour-ngx-bootstrap with Angular 7

### ISSUE THREAD

**Issue by SoniyaLadhani** [hakimio/ngx-ui-tour#16]
Facing  issues while running the application after making all the changes.
I am using Angular 7 with ngx-ui-tour-ngx-bootstrap

ERROR in node_modules/ngx-ui-tour-core/lib/tour.service.d.ts(2,15): error TS2304: Cannot find name 'UrlSegment'.
node_modules/ngx-ui-tour-core/lib/tour.service.d.ts(2,28): error TS2304: Cannot find name 'from'.
node_modules/ngx-ui-tour-core/lib/tour.service.d.ts(10,22): error TS2304: Cannot find name 'UrlSegment'.
node_modules/ngx-ui-tour-ngx-bootstrap/lib/tour-anchor.directive.d.ts(2,15): error TS2304: Cannot find name 'OnDestroy'.
node_modules/ngx-ui-tour-ngx-bootstrap/lib/tour-anchor.directive.d.ts(2,15): error TS2695: Left side of comma operator is unused and has no 
side effects.
node_modules/ngx-ui-tour-ngx-bootstrap/lib/tour-anchor.directive.d.ts(2,26): error TS2304: Cannot find name 'OnInit'.
node_modules/ngx-ui-tour-ngx-bootstrap/lib/tour-anchor.directive.d.ts(2,35): error TS2304: Cannot find name 'from'.
node_modules/ngx-ui-tour-ngx-bootstrap/lib/tour-anchor.directive.d.ts(10,65): error TS2304: Cannot find name 'OnInit'.
node_modules/ngx-ui-tour-ngx-bootstrap/lib/tour-anchor.directive.d.ts(10,73): error TS2304: Cannot find name 'OnDestroy'.

**Comment by hakimio** [comment]
Angular 7 is not supported. The oldest supported Angular version is 9.1 and the oldest supported TypeScript version is 3.8.
If you can't upgrade, you'll have to use [ngx-tour](https://www.npmjs.com/package/ngx-tour-ngx-bootstrap) version 4.2.1 or lower.

**Comment by SoniyaLadhani** [comment]
> rsion 4.2.1 or lower.

The documentation says in some places that the it supports Angular 2+. Kindly update it

**Comment by hakimio** [comment]
https://github.com/hakimio/ngx-ui-tour#about
