### ISSUE TITLE
🐞 - [service] Tour won't open again after pressing the "prev" button and then closing it (with optional first step)

### ISSUE THREAD

**Issue by alex4ndern** [hakimio/ngx-ui-tour#165]
### Which ngx-ui-tour-* package is the source of the bug?

ngx-bootstrap

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wau2z8?file=src%2Fapp%2Fui-tour-demo.component.ts

### Description

To reproduce the problem:
1. Go to the demo link
2. Make the first step optional with `isOptional: true`
3. Remove the anchor `tourAnchor="start-button"` from the button in the template 
4. Click the button (you get sent to step 2, because the anchor for step 1 doesn't exist)
5. Click on Next
6. Click on Prev
7. Close the Tour
8. Try to open it again

Expected: To get redirected to step 2 again and start the Tour again
Observed: Nothing happens when trying to start the Tour again

The reason behind the issue is that when we click on the Prev button we are setting the `direction` property in the service to `backwards` and when we close the Tour and reopen it, the direction is still set to backwards, and because the Tour tries to figure out which one is the first step (because our first step doesn't exist, on index 0), it looks for the direction to know should It search for the next step or for the prev step and because the direction is set to backwards, it tries to go to the previous step that doesn't exist, resulting in this problem.
Not sure if the direction value was intended to persist even after the Tour is closed, because if it was resetting to `forwards` it would've solved the issue (but maybe it can cause other issues?) 

For now my workaround is to call `tourService.next()` when I close the Tour, to ensure that the direction goes back to `forwards`, it produces a warning, but that's the simplest solution I have found so far.

### Angular version

17.0.9

### Ngx UI Tour version

14.0.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
PR is welcome.

**Comment by alex4ndern** [comment]
Will put up one in the following days
