### ISSUE TITLE
🐞 - Ionic Version 3 doesn't support Ionic Non-Standalone Ionic Apps

### ISSUE THREAD

**Issue by selected-pixel-jameson** [hakimio/ngx-ui-tour#166]
### Which ngx-ui-tour-* package is the source of the bug?

ionic

### Description

I've updated my Ionic App to use the latest version of Ionic [ 7.6.x ] and Angular 17. However, I'm not implement Ionic's standalone components yet because this would require a tremendous amount of effort to migrate all of the components in my application as it is very large. 

With that said I still want to update to the latest version of Angular so that my dependencies aren't out of date.

The latest Ionic version of this library uses standalone Ionic components. But since my Ionic App is not setup to use standalone components this causes issues because I'm loading the IonicModule instead of the standalone components. 

Ionic now providers a starter template for both "standalone" and "module" based applications. 

Can we update the library so that it also supports both? 

### Angular version

17.x.x

### Ngx UI Tour version

3.x.x

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
What issue exactly are you facing with the new version of the library in app module app? Can you provide some reproduction, errors you are experiencing?

**Comment by hakimio** [comment]
BTW, they have a script to automatically convert non-standalone Ionic app into standalone. Have you tried it?

**Comment by selected-pixel-jameson** [comment]
Actually, no I cannot provide any errors. There were none being thrown. The styles for the Ionic components were simply not being loaded. 

As I've stated and confirmed with the Ionic team. If my Ionic application is setup to use angular modules, specifically the IonicModule and not Ionic Standalone components this will result in issues. 

Since the updated ngx-ui-tour library for Ionic is using Standalone Ionic components and my Ionic application is not configured to use Ionic Standalone components this will cause issues and your library will not load correctly. 

My application is very larger and contains a lot of nested child routes. The migration tools only get me so far and then I have to go in and fix issues related to routing, child routing and nested routers. I spent a day trying to migrate it all and was still running into issues at the end of that day.

**Comment by hakimio** [comment]
In that case, you should be able to use the old version of the library with Angular 17 even the peer dependencies don't match.
I have no plans to maintain two separate versions of Ionic UI.

**Comment by selected-pixel-jameson** [comment]
I'm pretty sure that when I try to install the older version it throws NPM errors. I'm fine with that, but I just can't install it.

**Comment by hakimio** [comment]
Just use npm with `--legacy-peer-deps`. You can set it in npm config file as well.
