### ISSUE TITLE
Cannot position tour-element by config property

### ISSUE THREAD

**Issue by Tombalabomba03** [hakimio/ngx-ui-tour#17]
This is propably more of a featurerequest than a bug.

I cannot find any property in step-configuration that lets me manipulate the position of the step-element.
I would like to configure weather it is shown left, right, over or under the element it is anchored to.

`this._tourService.initialize([
            {
                anchorId: 'dashboard-centered',
                title:  'super cool title'),
                content: 'super cool content',
                route: '/dashboard'
                position: right
            }
])`

or even better, have position be an object that contains additional values to position relative to anchor-element

As a workaround i currently read the height and width of the anchor-element and use it to manually position 
.cdk-overlay-connected-position-bounding-box.

I love the library, thanks to everyone who contributed!

**Comment by hakimio** [comment]
`ngx-ui-tour-md-menu` doesn't support positioning yet. I'll see if this can be implemented sometime soon.

**Comment by hakimio** [comment]
You can now configure step position in [v6.1](https://github.com/hakimio/ngx-ui-tour/releases/tag/v6.1.0).

**Comment by Tombalabomba03** [comment]
Thank you for your quick reaction and update! 
I updated my verstion of the library and found that only the xPosition works, when i try to add placement with yPosition: 'above' the step still shows up under the touranchor (even though there is more than enough space above it).
Also even if everything works great, it is not possible to place the step completely after the touranchor, since it behaves the same as mat-menu positioning. 
It would be great to have the the option to determine weather the step should show up behind the touranchor, plus an additional property to set a margin between anchor and step, and an additional property to set if the step should be shown, centered or top-aligned/bottom-aligned, and if there is an arrow pointing towards the tourAnchor:

`import {IStepOption} from 'ngx-ui-tour-md-menu';

const steps: IStepOption[] = [{
    anchorId: 'start.tour',
    content: 'Welcome to the Ngx-UI-Tour tour!',
    title: 'Welcome',
    placement: {
       xPosition: 'after | before | center | alignLeft | alignRight',
       yPosition: 'center | alignTop | alignBottom | above | below ',
       margin: '5px',
    },
    arrow: true
}];`

I am considering to contribute, however i'm not sure if its not easier to just dump the whole mat-menu infrastructure plus i have zero experience in creating libraries ... do you think it would be possible for me to add all that functionality?

**Comment by hakimio** [comment]
> I updated my verstion of the library and found that only the xPosition works, when i try to add placement with yPosition: 'above' the step still shows up under the touranchor (even though there is more than enough space above it).

We are using [Angular Material Menu xPosition and yPosition](https://material.angular.io/components/menu/api#MatMenu). If the Menu component determines, that there isn't enough space on top, it will be displayed on the bottom. If there is definitely enough space, the only other reason I can think of is misspelling in `yPosition` config key or value.

> It would be great to have the the option to determine weather the step should show up behind the touranchor

Not sure I understand where exactly you want to place the tour step. How can it be behind tour anchor element?

> plus an additional property to set a margin between anchor and step

You should be able to do that using `touranchor--is-active` global CSS class. Sth like the following:
```css
.touranchor--is-active {
    padding-top: 1.5rem;
    margin-top: -1.5rem;
}
```

> and an additional property to set if the step should be shown, centered or top-aligned/bottom-aligned, and if there is an arrow pointing towards the tourAnchor:

For that you'll have to use another tour UI like [ng-bootstrap](https://hakimio.github.io/ngx-ui-tour/ng-bootstrap) or [ngx-bootstrap](https://hakimio.github.io/ngx-ui-tour/ngx-bootstrap). That's not possible with `md-menu`.

> I am considering to contribute, however i'm not sure if its not easier to just dump the whole mat-menu infrastructure plus i have zero experience in creating libraries ... do you think it would be possible for me to add all that functionality?

To be honest, I don't think so. If you are not happy with this library, you can also take a look at some alternatives like [ng-tour](https://github.com/P1N2O/ng-tour) or [ngx-joyride](https://github.com/tnicola/ngx-joyride).
