### ISSUE TITLE
🚀 - Multi Tour and Execute function before loading step.

### ISSUE THREAD

**Issue by danielmosss** [hakimio/ngx-ui-tour#170]
### Which ngx-ui-tour-* package is relevant to the feature request?

md-menu

### Description

1. multi tour
For my angular project i would like to have 4 different ui tours. Because i have four seperate things i want to demo. 

2. function before loading step
Im also looking for a way to execute a function before the step is loaded. for example that i can add a function to the step by initialization and that function can then be executed resulting in a popup that will be opened and then the touranchor is visable and it woulnd crash or stop.

**Comment by hakimio** [comment]
1. you can just re-initialize the tour multiple times with different steps. I don't see any value of being able to run multiple tours at the same time.
2. use `async` step and listen to `stepHide` event of the previous step (also, might be a good idea to check `direction` param).

**Comment by danielmosss** [comment]
Oke, thank you for you reply.
So i can initialize tour 1. And then when i want to run tour 2 i can just before i start tour 2 run: this.tourService.initialize(this.tourSteps2);

**Comment by hakimio** [comment]
yes.

**Comment by danielmosss** [comment]
Allright, im going to try this again. 
Maybe I did something wrong the last time i tried this. Will update you.

**Comment by danielmosss** [comment]
The solution you presented works fine. Thank you for that.

I came across this bug. The anchor tag is on the button.
![image](https://github.com/hakimio/ngx-ui-tour/assets/121039995/856798e1-0f5a-4357-b282-fdc87994a142)
![image](https://github.com/hakimio/ngx-ui-tour/assets/121039995/3211a4a8-99e9-4515-b9a2-a47dc991a998)

**Comment by hakimio** [comment]
The issue is mentioned in the release notes: [v12 announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v12.0.0#:~:text=md%2Dmenu%3A%20tour%20step,hidden%20using%20showArrow%20config.)

**Comment by danielmosss** [comment]
Allright thanks for you quick support.

**Comment by danielmosss** [comment]
The multi ui tour works, but when run tour 1 and then close it and run tour 2 the X button and the End button woulnd close the ui tour. 
In console i get the message that the tour 2 steps are initialized.

**Comment by hakimio** [comment]
Please create a new bug report with reproduction.
