### ISSUE TITLE
angular material installed, it doesn't build

### ISSUE THREAD

**Issue by CleverMobile2811** [hakimio/ngx-ui-tour#18]
Error: node_modules/@angular/material/button/button.d.ts:21:22 - error TS2420: Class 'MatButton' incorrectly implements interface 'CanColor'.
  Type 'MatButton' is missing the following properties from type 'CanColor': color, defaultColor

**Comment by hakimio** [comment]
The error is coming from Angular Material library, not ngx-ui-tour. If you can create a simple reproduction, maybe you should report it to Angular Material project.

**Comment by hakimio** [comment]
The problem seems to be that [you are using an old version of TypeScript](https://github.com/angular/components/issues/23166#issuecomment-879980477).

**Comment by CleverMobile2811** [comment]
Type script version?
