### ISSUE TITLE
🚀 - Improve step arrow positioning

### ISSUE THREAD

**Issue by danipavic** [hakimio/ngx-ui-tour#181]
### Which ngx-ui-tour-* package is relevant to the feature request?

md-menu

### Description

Currently, it seems that the step arrow is always shown in one particular position depending on the orientation of the step relative to the anchor element. In most of the situations, the arrow is positioned incorrectly and it looks bad, which forces me to disable arrows on all steps.

The library should either position the arrow better or allow the user to set custom positions eg. start, center, end, etc.

![Screenshot 2024-05-27 at 11 03 29](https://github.com/hakimio/ngx-ui-tour/assets/35301355/5ad93636-bda0-4183-bdac-05292e90abde)

**Comment by hakimio** [comment]
You can use `placement` config to fix the arrow position.

**Comment by danipavic** [comment]
Thanks, it wasn't super logical to me, but 

```
placement: {
      yPosition: 'above',
},
```

works. I initially tried to resolve this with this approach but I used `xPosition`. It might be a good idea to document this somehow, I am not sure people will go and read all of the release docs to find information.

**Comment by hakimio** [comment]
PRs to improve documentation are welcome.
`xPosition` and `yPosition` are documented in [Angular Material docs](https://material.angular.io/components/menu/api#MenuPositionX:~:text=outside%20the%20component.-,%40Input(),xPosition%3A%20MenuPositionX,-Position%20of%20the).
