### ISSUE TITLE
🚀 - Support Angular v18

### ISSUE THREAD

**Issue by voi99** [hakimio/ngx-ui-tour#182]
### Which ngx-ui-tour-* package is relevant to the feature request?

md-menu

### Description

Add support for Angular v18

**Comment by devonacode** [comment]
+1

**Comment by Kinqdos** [comment]
+1

**Comment by hakimio** [comment]
Support for Angular v18 is coming after [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap/issues/4703) releases their new version with Angular 18 support.

**Comment by NithishCirigidda** [comment]
+1

**Comment by shamoon** [comment]
Really appreciate this project and all the work by the maintainers. I'm sure you know but just in case not, https://github.com/ng-bootstrap/ng-bootstrap/releases/tag/17.0.0 is out =)

**Comment by veneliniliev** [comment]
+1

**Comment by hakimio** [comment]
`v13` has been released. Check out [the release announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v13.0.0).
