### ISSUE TITLE
🐞 - `tourService.steps?.length` doesn't ignore optional steps

### ISSUE THREAD

**Issue by ajaykarwal** [hakimio/ngx-ui-tour#188]
### Which ngx-ui-tour-* package is the source of the bug?

ngx-bootstrap

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wau2z8-cayq97?file=src%2Fapp%2Fui-tour-demo.component.html

### Description

I have a tour which shows off features of our app, with some optional steps which are shown depending on the users subscription level.
The tour all works fine and ignores the optional steps if the feature is not available to the user, however I'm also using the progress tracker on my tour template and the progress counter doesnt adjust accordingly.

For example, my tour has 4 steps.
User 1 has all 4 features enabled, so the progress tracker shows `1/4, 2/4, 3/4, 4/4`
User 2 doesn't have the 2nd feature available. They see `1/4, 3/4, 4/4`, but I would like them to see `1/3, 2/3, 3/3`

Is this possible in any way?

I've tried filtering the tourSteps before calling `initialize` but this only works when all the tourAnchors are on one page. It fails if there's a route change.

### Angular version

17.3.11

### Ngx UI Tour version

12.0.2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
`tourService.steps?.length` can not and should not ignore optional steps. That's not a bug.
Why exactly the step filter approach doesn't work for you? What fails exactly when the route changes?

**Comment by ajaykarwal** [comment]
the route change was failing becuase I was trying to filter out steps based on registered anchors, but since the anchors on the new route were not registered yet, the corresponding steps were being filtered out so when the route changes I got an error saying the element cannot be found (dont remember the exact error) - so i've scrapped that approach.

For now I've got a work around by creating a duplicate tour with the missing step based on the users settings but it not a nice solution, it would be great if the progress counter could somehow show the correct count.

**Comment by hakimio** [comment]
I don't think that's possible since, as you mentioned yourself, at the start of the tour you can not be sure that all tour anchors have been registered already.
If you can come up with a solution which takes into account the issues you've encountered, feel free to create a PR.
