### ISSUE TITLE
does not work with typescript4.1

### ISSUE THREAD

**Issue by CleverMobile2811** [hakimio/ngx-ui-tour#19]
Why it doesn't work with typescript4.1?
The package: available Angular9+
But it doesn't work with Angular11/typescript4.1.6

**Comment by hakimio** [comment]
ngx-ui-tour does work with TS 4.1. If latest version of Angular Material requires TS 4.2, that's a different issue. I don't have control of Angular Material library. If you can't upgrade TS, use older version of Angular Material or complain to them about this issue.

**Comment by CleverMobile2811** [comment]
it doesn't work with TS4.1
