### ISSUE TITLE
🐞 - NGX tour should add in ag-grid

### ISSUE THREAD

**Issue by Poulami1998** [hakimio/ngx-ui-tour#191]
### Which ngx-ui-tour-* package is the source of the bug?

ngx-bootstrap

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wau2z8?file=src%2Fapp%2Fui-tour-demo.component.ts

### Description

How to add tour ui in ag grid header and cells, please help me for this.

### Angular version

16.1.0

### Ngx UI Tour version

11.0.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
https://github.com/hakimio/ngx-ui-tour/discussions/50#discussioncomment-2378780
