### ISSUE TITLE
🚀 - Support Angular v19

### ISSUE THREAD

**Issue by ivanpopovicib** [hakimio/ngx-ui-tour#197]
### Which ngx-ui-tour-* package is relevant to the feature request?

md-menu

### Description

Add support for Angular v19

**Comment by Laess3r** [comment]
Hi! Just as an information: ngx-bootstrap 19.0.1 was released today [https://github.com/valor-software/ngx-bootstrap/issues/6710](https://github.com/valor-software/ngx-bootstrap/issues/6710).

**Comment by hakimio** [comment]
I'll try to release a new version next week.
Pretty busy now.

**Comment by rubenCodeforges** [comment]
Guys you know that PRs are welcome ?
I mean everyone can ask , but also you can contribute.

**Comment by grzel4000** [comment]
Any luck with the update? It would be greatly appreciated. Thanks

**Comment by hakimio** [comment]
Working on it 😉

**Comment by grzel4000** [comment]
Great news! Thanks!

**Comment by hakimio** [comment]
`v14` has been released. Check out [the release announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v14.0.0).
