### ISSUE TITLE
Feature request: Use of positions ConnectedPosition[] within placement attribute

### ISSUE THREAD

**Issue by baldemarch** [hakimio/ngx-ui-tour#33]
Library looks great, but I feel it lacks a bit of positioning options like the ones described here in https://material.angular.io/cdk/overlay/api#CdkConnectedOverlay

Would it be possible to have this in a future version?

Thanks!

**Comment by hakimio** [comment]
Hi @baldemarch 

All positioning options are based on underlying UI components. `mat-menu` component has [`xPosition` and `yPosition`](https://material.angular.io/components/menu/api#MatMenu) options which are exposed via the `placement` option on step config. I don't have any plans to mess with `mat-menu` internals but if you can find _an elegant_ solution to introduce more positioning options, feel free to submit a PR and I'll try to review it ASAP.
Anyway, you can also take a look at other UI implementations like [Taiga UI hint](https://hakimio.github.io/ngx-ui-tour/tui-hint) or [Ngx Bootstrap](https://hakimio.github.io/ngx-ui-tour/ngx-bootstrap) if you need additional positioning options.
