### ISSUE TITLE
Using the Zone.js RxJS polyfill causes recursion issues

### ISSUE THREAD

**Issue by nickjillings** [hakimio/ngx-ui-tour#35]
There is a problem running the tours in apps with the Zone.js Rxjs polyfill included.

Here is a [repo](https://github.com/nickjillings/ngx-bootstrap-issue-5395) 
([and stack blitz ](https://stackblitz.com/github/nickjillings/ngx-bootstrap-issue-5395?file=src%2Fpolyfills.ts)).

It seems when the polyfill line `import 'zone.js/dist/zone-patch-rxjs'; ` is included this then throws all kinds of problems, mostly with it recursively calling across the two zones (<root> and angular). I've tried with both `ng-bootstrap` and `ngx-bootstrap`. Haven't used Material as our app uses bootstrap.

In the ngx-bootstrap it seems the directive being included causes the most issues. And in ng-bootstrap it's only when start is called that it throws the error.

**Comment by hakimio** [comment]
And without the tour all the `ng-bootstrap`/`ngx-bootstrap` components/directives used here work as they should? The `popover` directive itself is not causing those issues?

**Comment by hakimio** [comment]
To be honest, I would likely blame [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap/issues/2522#issuecomment-405169483) and the polyfill itself for this issue. Don't have the time or will to investigate it more at the moment.
If you find a simple fix, feel free to open a PR.

**Comment by hakimio** [comment]
Closing since I don't think this is an issue with the `ngx-ui-tour` itself but 3rd party library (`ng-bootstrap`).
Possible solutions/workarounds:
- Don't use the polyfill
- Create a bug report in `ng-bootstrap` library to see if they care
- Use another UI implementation
