### ISSUE TITLE
ngx-ui-tour-core dependency

### ISSUE THREAD

**Issue by Wasabi375** [hakimio/ngx-ui-tour#36]
I was wondering if there is any good reason not to add ngx-ui-tour-core as a dependency in this project. This way you could install this with just one `npm i --save` command instead of 2.
I just ran into this issue when someone in our team accidentally only commited the `ngx-ui-tour-md-menu` entry in our package.json file. Obviously this was easily fixed, but it would still be nice if the core dependency is automatically installed by npm.

**Comment by hakimio** [comment]
`npm v7` automatically installs peer dependencies. Are you still using v6?
Anyway, your suggestion makes sense to me and I will most likely do it in the next major release.

**Comment by Wasabi375** [comment]
For some reason I still have npm 6 on my computer. I was sure I was using the latest version, but maybe I missed upgrading on this computer. Thanks for the tip. I wouldn't have thought to check the npm version.

**Comment by hakimio** [comment]
Remember to star the project if you like it.
