### ISSUE TITLE
Kind request to publish an Ivy distribution

### ISSUE THREAD

**Issue by IgnacioHR** [hakimio/ngx-ui-tour#37]
I would like to kindly request a solution to this comment from the compiler:

```
Processing legacy "View Engine" libraries:
- ngx-ui-tour-core [es2015/esm2015] (https://github.com/hakimio/ngx-ui-tour.git)
- ngx-ui-tour-md-menu [es2015/esm2015] (https://github.com/hakimio/ngx-ui-tour.git)
- ngx-ui-tour-core [main/umd] (https://github.com/hakimio/ngx-ui-tour.git)
- ngx-ui-tour-md-menu [main/umd] (https://github.com/hakimio/ngx-ui-tour.git)
Encourage the library authors to publish an Ivy distribution.
```

I tried to do it myself but it looks like the code around the library (but not the library itself) depends too much on Taiga UI and I failed to update the project because of the dependencies.

Note I'm using the library in a project in Angular 13

Thank you in advance!

**Comment by hakimio** [comment]
I'll release v8 with Ivy partial compilation format this or next week.

**Comment by IgnacioHR** [comment]
Great news!
Thank you so much

**Comment by hakimio** [comment]
Try out v8 and let me know if it works as expected.

**Comment by hakimio** [comment]
Remember to star the project if you like it.
