### ISSUE TITLE
how to get input like "click" then move to next pop-up ? 

### ISSUE THREAD

**Issue by lmk07** [hakimio/ngx-ui-tour#40]
i'm trying to implement ngx-ui-tour in my application. 

1) i want "user" to click a element mandatory, then move to next popup, is it possible to implement it in ngx-ui-tour.

2) i want to change position of popup , i tried in below way

```
this.tourService.initialize([{
            anchorId: 'some.anchor.id',
            content: 'Select Product',
            title: 'step 1'
          }],{
          enableBackdrop: true,
          placement : 'right'
 });
```
 but it showing error.

3) how can i not showing "Prev" and "Next" button in popup?

4) Also how can i route based on the button click?

Thanks in advance.

**Comment by hakimio** [comment]
1. You have to add click listener on the element and then use `TourService` to navigate to the next step
2. Which tour UI are you using? If it's `md-menu`, you can try the following config (placement config will only be applied if there is enough space):
```ts
this.tourService.initialize([{
    anchorId: 'some.anchor.id',
    content: 'Select Product',
    title: 'step 1'
}], {
    enableBackdrop: true,
    placement: {
        xPosition: 'before',
        yPosition: 'above'
    }
});
```
Check [md-menu docs](https://material.angular.io/components/menu/api#material-menu-type_aliases) for more info.
3. You have to create [custom step template](https://hakimio.github.io/ngx-ui-tour/md-menu/Misc#custom-template).
4. If you need dynamic steps/step configs, you might have to reinitialize the tour to update the steps and then use `tourService.startAt(stepIdOrIndex)` to start at specific step. Another option in your case might be to change route manually and then use tourService to show correct tour step once the page is loaded.

**Comment by lmk07** [comment]
Hi 
tourService.startAt(stepIdOrIndex).      in this "stepIdorIndex" means "anchorId: 'some.anchor.id'" or something else ????

**Comment by hakimio** [comment]
@lmk07 No, it's either the [`stepId` config](https://hakimio.github.io/ngx-ui-tour/md-menu/API) or step's index in your steps array.

**Comment by hakimio** [comment]
- If your component loads after `tourService.next()` call, you might find `isAsync` config useful
- To listen to `initialized` event you can use [`initialize$` event observable](https://hakimio.github.io/ngx-ui-tour/md-menu/API#events)

If you can recreate your scenario on Stackblitz or in a public Github repo, I could take a look at it, but I don't have time to write a full new demo app for you.

**Comment by lmk07** [comment]
Yeah sure @hakimio  i will recreate my scenario in stackblitz and inform you.
And by the way 

### **If your component loads after tourService.next() call, you might find isAsync config useful**
can you give simple syntax code for this next() and how can i use it like that.

**Comment by hakimio** [comment]
[`isAsync`](https://hakimio.github.io/ngx-ui-tour/md-menu/API#step-config) is a step config used for steps where anchor element is added to DOM with a delay:
```js
{
    anchorId: 'start.tour',
    content: 'Welcome to the Ngx-UI-Tour tour!',
    title: 'Welcome',
    isAsync: true
}
```
`next()` is TourService method: `this.tourService.next()`.

**Comment by lmk07** [comment]
HI @hakimio  
i have recreated the scenario, please use this link 
[https://stackblitz.com/edit/angular-ivy-sowfty?file=src/app/app.module.ts](https://stackblitz.com/edit/angular-ivy-sowfty?file=src/app/app.module.ts)

Below is the flow

1) i want to highlight Menu 1 
2) in this blue box  i want to highlight **"product"** , then **"Entitytype"**
3) i want use to click **"search"** button
4) then i want to highlight **table**
5) then **download** button
6) then **Menu 2**
7) then in Red box --> select product and select platform

this is how i want to do. i try to implement ngx-ui-tour in that project but when i add it in module im getting error in main.ts file

**Comment by lmk07** [comment]
hi @hakimio  i try to install ngx-ui-tour in stackblitz project but im getting  following error , but im my local im able to set it properly...
<img width="1011" alt="Screenshot 2022-02-08 at 3 06 32 PM" src="https://user-images.githubusercontent.com/66107540/152960007-294be7b7-6bb2-4e87-a3a7-42e78519be86.png">

**Comment by hakimio** [comment]
No, idea. Might be some stackblitz bug. You can always download and try the same project locally to see if it's an issue with stackblitz.

**Comment by lmk07** [comment]
hi @hakimio , did you had a time to look at my project in stackblitz?

**Comment by lmk07** [comment]
hi @hakimio suppose if stackblitz is not support for ngx-ui-tour, please just insert your code in project, i will take it from stackblitz and implement it in local system and try it. thanks

**Comment by hakimio** [comment]
@lmk07 the problem I see with your scenario is that you want user to click on UI elements when the UI tour backdrop is active, but the backdrop blocks any interaction with your site since it covers everything.

**Comment by lmk07** [comment]
@hakimio ok i got it. what about , if i disable backdrop completely and i want user to click the search button then i wait for the element to load  then move to next anchorId, is this possible?

**Comment by lmk07** [comment]
@hakimio  is it possible to customize the backdrop css?

**Comment by hakimio** [comment]
@lmk07 You can use `ngx-ui-tour_backdrop` CSS class in your global `styles.scss` to customize the backdrop:
```css
.ngx-ui-tour_backdrop {
    z-index: 999 !important;
}
```
