### ISSUE TITLE
Step with longer content overlaps anchor element

### ISSUE THREAD

**Issue by Shaent** [hakimio/ngx-ui-tour#42]
Hi!

First of all I would like to thank you for your great library!

I think I found a bug though. I have created a custom tour step template which can hold a picture and is generally designed to hold more content (like 2 - 3 sentences).

The problem is that the step kind of "hits" the bottom edge of the screen because of the longer content and thus does overlaps the anchor element instead of placing itself below it. I provided a screenshot which I hope will make my issue more clear.

![image](https://user-images.githubusercontent.com/40316889/155155299-f4f9ab8d-ab4a-468d-859c-3520f53ba16a.png)

If you need any more information please let me know.

**Comment by hakimio** [comment]
Hi,

This is not a bug with this library. That's just how Angular material menu component works. You can check it out yourself [here](https://stackblitz.com/edit/angular-vszznc?file=src/app/menu-icons-example.html). Also, if the step card went down over the screen edge to reveal anchor element, "Back" and "Next" buttons would be hidden. That would be even worse.
