### ISSUE TITLE
Styling of the mat menu panel

### ISSUE THREAD

**Issue by Shaent** [hakimio/ngx-ui-tour#43]
Hi,

Right now I am using the html id mat-menu-panel-0 to style the div element that acts as the background of every tour step (This element is created by the mat-menu component). I cannot use the class mat-menu-panel as this would obviously style every other menu background panel. 

I am wondering if teh id mat-menu-panel-0 is actually always unique to every step or if it would be possible to provide an additional custom class name/id to said element?

**Comment by hakimio** [comment]
You can just use CSS selector `.mat-menu-panel.tour-step` to target the tour step panel.

**Comment by Shaent** [comment]
Thanks. Works as expected. Don't know why I did not try that selector 😄.
