### ISSUE TITLE
Is it possible to get the id/anchorId of the upcoming step before loading it?

### ISSUE THREAD

**Issue by paulchartres** [hakimio/ngx-ui-tour#46]
I am trying to trigger an action (click a button) as soon as the user presses "Next" on the tour, in order to show elements that are hidden before reaching this step. There's an observable for when the step is _shown_, but not triggered, it seems. Is there a way for me to achieve this?
Awesome work on this by the way, it looks and feels amazing. :)

**Comment by hakimio** [comment]
Both `stepShow$` and `stepHide$` event observables should be working as expected. Can you create a demo showing that they are not triggering in some case?

**Comment by paulchartres** [comment]
I am very deeply sorry, it seems like this observable indeed does what I was looking for! The problem came from the fact I was using the isAsync property while never making the DOM element appear... Thanks a lot for the quick response however!

**Comment by hakimio** [comment]
You are welcome. Remember to star the library if you like it :)
