### ISSUE TITLE
Tip is not working properly on resize

### ISSUE THREAD

**Issue by directcuteo** [hakimio/ngx-ui-tour#5]
Hello!
I am using this awesome library within an Angular 10 app.
The issue I have with it is that on resize it is broken. Please note that this happens only when using the backdrop.
Without the backdrop, the tooltip follows its element flawlessly like on the demo page, but when you enable the backdrop, the backdrop itself is not updating accordingly, which results in it covering the highlighted element.

Thanks!

**Comment by hakimio** [comment]
Will be fixed in next minor release.

**Comment by hakimio** [comment]
@directcuteo 
I have published v5.1. Test it out and let me know if it fixes your issue.

**Comment by directcuteo** [comment]
Thank you for your update!
Now it seems that when I resize, the first element (of the steps) gets focused instead of the currently active element.
The good thing is that the overlay doesn't overlap the element on resizing, but the problem is that it is always the first element that gets highlighted on the smallest window resize.

**Comment by hakimio** [comment]
Ok, I think I see why this is happening.

**Comment by hakimio** [comment]
I have released v5.1.1 Can you test it?

**Comment by directcuteo** [comment]
Now it's working great. Do you think there is a way to focus the element even if it goes out of the view because of resizing? Think of a layout with 2 columns where on resize, the second column goes under the first one and it is not longer visible. If the second column is highlighted by Ui Tour it won't scroll to remain in view (and I can't scroll either because of the backdrop). But if the resizing is done before focusing on that second column (for example when focusing on the first column), the library scrolls to it when it is the second column's turn to be focused, so this case works and actually it's visible on the demo page.

**Comment by hakimio** [comment]
@directcuteo I understand what you mean, but, I think, it's not directly related to this bug report. Can you open a new bug report for automatic page scroll on page resize? I'll take a look when I have time.

**Comment by directcuteo** [comment]
sure, thanks again for solving this!
