### ISSUE TITLE
Error integration with CLI

### ISSUE THREAD

**Issue by sh977218** [hakimio/ngx-ui-tour#51]
Hi, I'm using angular cli 12 generated project. But I'm seeing an error:
```
ERROR in ./node_modules/ngx-ui-tour-core/fesm2020/ngx-ui-tour-core.mjs 7:0-69
Module not found: Error: Can't resolve 'rxjs/operators' in 'C:\Users\huangs8\workspace\cde\node_modules\ngx-ui-tour-core\fesm2020'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'rxjs/operators' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./node_modules/ngx-ui-tour-md-menu/fesm2020/ngx-ui-tour-md-menu.mjs 3:0-39 4:0-135 18:30-41 109:12-39 135:49-62 147:45-58 152:349-371 159:238-260 166:40-67 198:16-35 199:16-27 209:8-18 215:8-18 218:12-22 223:11-21 235:24-34 239:24-34
 @ ./modules/_app/app.module.ts 41:0-69 66:16-41 87:16-27
 @ ./modules/_app/main.ts 3:0-44 15:41-53
```

Any idea where this error coming from?
Thanks!

**Comment by hakimio** [comment]
Do you have `rxjs` library installed? If yes, can you try to update to v7?

**Comment by hakimio** [comment]
I can't reproduce the issue. Seems to work fine with Angular v12 and Rxjs v6 for me. See the attached project for the demo.
Delete your `node_modules` and `package-lock.json`, update your `npm` to the latest version, reinstall and then try again. If the issue persists, please create a demo project reproducing the issue.

[ng-tour-test-angular-v12-rxjs-v6.zip](https://github.com/hakimio/ngx-ui-tour/files/8331765/ng-tour-test-angular-v12-rxjs-v6.zip)

**Comment by sh977218** [comment]
It's solved. Thanks!
