### ISSUE TITLE
Unexpected focus behaviour in navigation menu

### ISSUE THREAD

**Issue by Shaent** [hakimio/ngx-ui-tour#53]
Hi!

I am using you library to highlight some navigation items on our web page. I noticed an unexpected behavior regarding the :focus pseudo class of the navigation items.

It seems that the navigation item that has been highlighted before the current step has the pseudo class :focus assigned to it. This seems to be a little bit confusing for me as the users attention should solely be on the current highlighted tour step element. (See screenshot)

![image](https://user-images.githubusercontent.com/40316889/160375068-49e18d8e-2e44-4d31-9c01-6af12d3cbc35.png)

I also provided a [minimal example](https://github.com/Shaent/ng-tour-test) where you can take a look a the issue. It seems to be only the case for mat navigation items though. So maybe it has something to do with the material component and not your library.

**Comment by hakimio** [comment]
Fixed in v8.0.2
