### ISSUE TITLE
Creating a custom Step without Next Button

### ISSUE THREAD

**Issue by ChrTall** [hakimio/ngx-ui-tour#60]
I would like to create a custom Step component that has no next button, but is only used for some steps, which require user input in order to progress in the tour.
I read in other issues and the docs that you can use a Custom template, but I did not understand how I can create one and set it for a certain step as the template. Could you provide a little bit more detail on how to do that?

**Comment by hakimio** [comment]
You can just create one custom template for all steps and then hide the button depending which step you are on:
```html
<button
    mat-button
    class="next"
    *ngIf="tourService.hasNext(step) && step?.anchorId !== 'foo'"
    (click)="tourService.next()"
>
    {{step?.nextBtnTitle}} <mat-icon>chevron_right</mat-icon>
</button>
```

**Comment by ChrTall** [comment]
Thank you for your advice.

**Comment by ChrTall** [comment]
One thing that I had to do is use the default md-menu template instead of the default template of the README.md which is outdated I guess.
If you use the template from the Readme the close button is not styled properly. I wanted to create a Merge Request, but did not know which file I have to edit for the Readme.
