### ISSUE TITLE
Placing Tour Anchor inside MatDialog

### ISSUE THREAD

**Issue by ChrTall** [hakimio/ngx-ui-tour#61]
When I place a Tour Anchor at the top of a component which gets displayed as a MatDialog, the position of the Anchor is wrong.
I applied placement: {xPosition: "before", yPosition: "above"}.
Is there any way to display the tour modal above the actual MatDialog?

**Comment by hakimio** [comment]
The positioning is handled by [Angular Material Menu](https://material.angular.io/components/menu/overview) component. If the positioning doesn't work the way you expect, most likely that's not something that can be fixed in this library.

**Comment by ChrTall** [comment]
Okay, I was afraid that it wouldn´t work with MatDialogs. Thanks for your reply then I will manually position the Tour step with css like the centered tour element.
