### ISSUE TITLE
How to provide TourService in Component spec file?

### ISSUE THREAD

**Issue by kad-cornem** [hakimio/ngx-ui-tour#62]
When, I run a jasmine test the following error is thrown:
`NullInjectorError: R3InjectorError(DynamicTestModule)[NgxmTourService -> NgxmTourService]: 
  NullInjectorError: No provider for NgxmTourService!`

I tried providing it but this leads to additional errors.

**Comment by hakimio** [comment]
Take a look at issue #13. My guess is that you are importing the service from `ngx-ui-tour-core` instead of `ngx-ui-tour-md-menu`.

**Comment by kad-cornem** [comment]
It still seems to fail, this is the code in the test file:
```
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { NgxmTourService } from 'ngx-ui-tour-md-menu/lib/md-menu.module';



import { MapComponent } from './map.component';

describe('MapComponent', () => {
  let component: MapComponent;
  let fixture: ComponentFixture<MapComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [ MapComponent ],
      providers: [NgxmTourService]
    })
    .compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(MapComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

And im getting an error in the console that the module can't be found:

`./src/app/components/dashboard-module/map/map.component.spec.ts:3:0-83 - Error: Module not found: Error: Package path ./lib/ngx-md-menu-tour.service is not exported from package C:\Users\CornelisseMichael\OneDrive - Kadaster\Bureaublad\git\datascience-graphql-tijdreizen\node_modules\ngx-ui-tour-md-menu (see exports field in C:\Users\CornelisseMichael\OneDrive - Kadaster\Bureaublad\git\datascience-graphql-tijdreizen\node_modules\ngx-ui-tour-md-menu\package.json)`


But I can find the file under the node_modules.

**Comment by hakimio** [comment]
It's not exported. Meaning it's internal service which you can not use.
Why don't you just provide `TourService` from `ngx-ui-tour-md-menu`? Anyway, if you don't plan to mock the service, why don't you just import the whole `TourMatMenuModule` in your `TestBed`?

**Comment by kad-cornem** [comment]
The component I want to test injects the dependency of TourService , that's why I wan't to provide it otherwise it will give me the error.

Providing TourService, and adding  `imports:[RouterTestingModule]` solved it for me!
