### ISSUE TITLE
Update to Angular 14

### ISSUE THREAD

**Issue by fergardi** [hakimio/ngx-ui-tour#63]
Hello!

I was trying to update my project to Angular 14 and got errors in my tests regarding this module.
Are there any plans in upgrading the module to be compatible with Angular 14?

Thanks in advance.

**Comment by hakimio** [comment]
Hi,

What are the errors you are getting in your tests? Theoretically it should still work fine with Angular v14 even it's not marked as compatible.

There are still a lot of dependencies which don't have a stable version compatible with Angular 14, including the following:
- Taiga UI
- ngx-bootstrap
- ng-bootstrap

Most likely will look into updating `md-menu` UI implementation once PR #55 is merged.

**Comment by fergardi** [comment]
This is the error I'm getting after upgrading into Angular14 (both app running and the corresponding test):

```console
1) should CREATE the INSTANCE
     AppComponent
     NullInjectorError: R3InjectorError(DynamicTestModule)[TutorialService -> NgxmTourService -> Router -> Router]: 
  NullInjectorError: No provider for Router!
error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'TutorialService', 'NgxmTourService', 'Router', 'Router' ] })
NullInjectorError: R3InjectorError(DynamicTestModule)[TutorialService -> NgxmTourService -> Router -> Router]: 
  NullInjectorError: No provider for Router!
    at NullInjector.get (node_modules/@angular/core/fesm2015/core.mjs:9076:27)
    at R3Injector.get (node_modules/@angular/core/fesm2015/core.mjs:9243:33)
    at R3Injector.get (node_modules/@angular/core/fesm2015/core.mjs:9243:33)
    at injectInjectorOnly (node_modules/@angular/core/fesm2015/core.mjs:4849:33)
    at Module.ɵɵinject (node_modules/@angular/core/fesm2015/core.mjs:4853:12)
    at TourService_Factory (node_modules/ngx-ui-tour-md-menu/node_modules/ngx-ui-tour-core/fesm2015/ngx-ui-tour-core.mjs:271:1)
    at Object.factory (node_modules/ngx-ui-tour-md-menu/fesm2015/ngx-ui-tour-md-menu.mjs:20:1)
    at R3Injector.hydrate (node_modules/@angular/core/fesm2015/core.mjs:9338:35)
    at R3Injector.get (node_modules/@angular/core/fesm2015/core.mjs:9232:33)
    at injectInjectorOnly (node_modules/@angular/core/fesm2015/core.mjs:4849:33)
     Error: Expected undefined to be truthy.
    at <Jasmine>
    at UserContext.apply (src/app/app.component.spec.ts:47:23)
    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:26)
    at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:39)
```

This is my test:

```ts
beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule.withRoutes(routes),
        TourMatMenuModule.forRoot(),
        TranslateModule.forRoot(),
      ],
      declarations: [
        AppComponent,
      ],
      providers: [
        TourService,
        { provide: FirebaseService, useValue: FirebaseServiceStub },
      ],
      schemas: [
        CUSTOM_ELEMENTS_SCHEMA,
      ],
    }).compileComponents();
  }));
```

And this are some of my imports:

```ts
...
import { routes } from './app-routing.module';
import { TranslateModule } from '@ngx-translate/core';
import { RouterTestingModule } from '@angular/router/testing';
import { TourService, TourMatMenuModule } from 'ngx-ui-tour-md-menu';
...
```

It worked fine in Angular13, so I assumed it has something to do with the library, but maybe it's something about Angular14 itself, not sure.

Thanks in advance.

**Comment by hakimio** [comment]
Not sure why it doesn't just work when you provide `RouterTestingModule`. The only other option I see is to mock the `Router` yourself:
```
      providers: [
        { provide: Router, useValue: mockRouter }
      ]
```

**Comment by fergardi** [comment]
Unfortunately I have the same issues outside testing environment. After compilation and running the application, I got this error:

```console
ERROR NullInjectorError: R3InjectorError(AppModule)[TutorialService -> NgxmTourService -> Router -> Router -> Router]: 
  NullInjectorError: No provider for Router!
    Angular 6
    TourService_Factory ngx-ui-tour-core.mjs:271
    NgxmTourService_Factory ngx-ui-tour-md-menu.mjs:20
    Angular 4
    TutorialService_Factory tutorial.service.ts:7
    Angular 7
    AppComponent_Factory app.component.ts:14
    Angular 22
[core.mjs:6397:22](webpack:///node_modules/@angular/core/fesm2015/core.mjs)
    Angular 20
```

This is my TutorialService, used by my AppComponent:

```ts
import { Injectable } from '@angular/core';
import { TourService, IStepOption } from 'ngx-ui-tour-md-menu';

@Injectable({
  providedIn: 'root',
})
export class TutorialService {

  constructor(
    private tourService: TourService,
  ) { }

  ...
}
```

I believe it's all related to some new way of compiling or injecting dependencies in Angular14, but couldn't find a solution yet.

**Comment by hakimio** [comment]
Does it work if you try to inject the Angular Router yourself?
```
onstructor(
    private router: Router
  ) { }
``

**Comment by fergardi** [comment]
No, it appears to make no difference. Thanks for your suggestion anyway!

I'll continue to investigate if this same issues is happening with other libraries.

**Comment by hakimio** [comment]
Might be time to delete `package lock` file, `node modules` and reinstall everything ;)

**Comment by fergardi** [comment]
No luck so far...

Have you by any chance already tested the library with some angular14 project version?

**Comment by hakimio** [comment]
I have created a new Angular 14 project and it works as expected.
You have to install dependencies using [yarn v1](https://classic.yarnpkg.com/lang/en/): `yarn install`
[ng14-test.zip](https://github.com/hakimio/ngx-ui-tour/files/8974532/ng14-test.zip)

**Comment by fergardi** [comment]
I updated everything related to Angular again from v14.0.2 to v14.0.3, as well as this library version from v8.0.2 to v8.1.2 and suddenly everything started to work properly again.

Sorry for the inconvenience! And thanks for the help :)

**Comment by DotJoshJohnson** [comment]
I ran into this today (Angular `14.0.3` and ngx-ui-tour-md-menu `8.1.2`). The only way I could get this to work is by adding my own factory provider for the `TourService` service in `AppModule` (unrelated code removed):

```typescript
import { NgModule, RendererFactory2 } from "@angular/core";
import { Router } from "@angular/router";
import { TourMatMenuModule, TourService } from "ngx-ui-tour-md-menu";

import { AppComponent } from "./app.component";
import { AppRoutingModule } from "./app-routing.module";

@NgModule({
    declarations: [
        AppComponent,
        // ... //
    ],
    imports: [
        AppRoutingModule,
        TourMatMenuModule.forRoot(),
        // ... //
    ],
    providers: [
        { provide: TourService, useFactory: (router: Router, rendererFactory: RendererFactory2) => new TourService(router as any, rendererFactory), deps: [Router, RendererFactory2] }
        // ... //
    ],
    bootstrap: [
        AppComponent
    ]
})
export class AppModule { }

```

**Comment by hakimio** [comment]
Angular 14 is now supported in [v9 release](https://github.com/hakimio/ngx-ui-tour/releases/tag/v9.0.0).
