### ISSUE TITLE
Disable Hotkeys for interactive steps with disabled next button

### ISSUE THREAD

**Issue by ChrTall** [hakimio/ngx-ui-tour#66]
I have created a really nice guided tour with your library, thanks a lot.
I have some steps in my tour, which I call interactive steps. To progress in these steps the user has to click on highlighted UI Elements in order to progress in the guided tour. The Next button is hidden for these steps. It would be great if there were properties in the
IStepOption interface to disable certain hotkeys for a step. Right now the user can press the next button to progress without clicking on the UI Element.

**Comment by hakimio** [comment]
Right now you can manually call `tourService.disableHotkeys()` to disable hotkeys, but it might be a good idea to automatically disable hotkeys when `goToNextOnAnchorClick` is enabled and allow user to disable hotkeys for certain steps.

**Comment by hakimio** [comment]
This has been implemented in [v9 release](https://github.com/hakimio/ngx-ui-tour/releases/tag/v9.0.0).
