### ISSUE TITLE
Step content not showing

### ISSUE THREAD

**Issue by jpngeekudin** [hakimio/ngx-ui-tour#69]
Step content is not showing, only showing modal with title and blank body.
I am using ngx-ui-tour-ng-bootstrap@10.1.2

Here is my code

```
// app.component.ts
this.tour.initialize([
  {
    anchorId: 'processor-create-batch',
    content: 'Create batch for the first time asdasdasdasdasdasdasdasd',
    title: 'Create Batch Ululu',
    route: '/job/home',
  },
  {
    anchorId: 'processor-receive-batch',
    content: 'For receiving batch from farmer',
    title: 'Receive Batch',
    route: '/job/home',
  },
]);
this.tour.start();
```

```
// app.modules.ts
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgbModule,
    HttpClientModule,
    BrowserAnimationsModule,
    TourNgBootstrapModule.forRoot(),
  ],
  ...
})
```

![image](https://user-images.githubusercontent.com/74789463/179465424-04227429-c2b2-4bdb-a81e-f9e80d6f5c7a.png)

**Comment by hakimio** [comment]
Did you add tour-step-template component like it says in the README: https://hakimio.github.io/ngx-ui-tour/ng-bootstrap/Setup#simple-project

**Comment by jpngeekudin** [comment]
Ah yeah, it's showing after I added tour-step-template component.
Thank you so much!
