### ISSUE TITLE
Tour won't start on child page

### ISSUE THREAD

**Issue by buddyackerman** [hakimio/ngx-ui-tour#71]
I'm using Angular 13 with ngx-ui-tour-ng-bootstrap v8.1 and ngx-ui-tour-core 6.1.  I'm trying to setup the tour to start on s child page because I have to only start it after the user has authenticated.  So, I put the `<tour-step-template></tour-step-template>` element in the child page and I have initialized and started the TourService in this child page like so:

    this.tourService.initialize([
      {
        anchorId: 'landingpage.new',
        content: 'Start a new investigation',
        title: 'New Invesgtigation',
        route: '/home/landing-page'
      },
      {
        anchorId: 'landingpage.list',
        content: 'Here is the list of investigations',
        title: 'Invesgtigations',
        route: '/home/landing-page'
      }

    ],
    {
      enableBackdrop: true
    });
    this.tourService.start();

In the landing page HTML I have these two elements 

    <button tourAnchor="landingpage.new" class="m-0 btn btn-primary d-flex align-items-center flex-00a"

    <table tourAnchor="landingpage.list" (matSortChange)="sortData($event)" class="assessment-summary" style="overflow-x:auto">

When I debug on the line where I call `tourService.start()` the tour service shows that it is configured with the tour steps that I defined yet the tour never starts up.  What am I doing wrong?

**Comment by hakimio** [comment]
- You can't mix and match different versions of `ngx-ui-tour-ng-bootstrap` and `ngx-ui-tour-core`. Anyway, since v8, you no longer  have to install `ngx-ui-tour-core` separately since it's now a "hard" dependency of the `ngx-ui-tour-ng-bootstrap`.
- As stated in [the installation guide](https://hakimio.github.io/ngx-ui-tour/ng-bootstrap/Setup#lazy-loaded-modules) `<tour-step-template></tour-step-template>` should be added to the root app component.
- Make sure that the anchors added to your html elements match exactly the ones in your tour steps.
- Carefully investigate [the demo app](https://github.com/hakimio/ngx-ui-tour/tree/master/projects/lazy-tour-demo/src/app).
- If you still can't make it work, create a GitHub repo with the reproduction of the issue.

**Comment by buddyackerman** [comment]
When I originally installed `ngx-ui-tour-ng-bootstrap` it did not install any version of `ngx-ui-tour-core`.  I then manually installed version 8.1 of `ngx-ui-tour-core`.  That resulted in me getting the following error when compiling

    Error: node_modules/ngx-ui-tour-ng-bootstrap/lib/tour-anchor.directive.d.ts:13:22 - error TS2420: Class 
    'TourAnchorNgBootstrapDirective' incorrectly implements interface 'TourAnchorDirective'.
      Property 'element' is private in type 'TourAnchorNgBootstrapDirective' but not in type 'TourAnchorDirective'.
    
    13 export declare class TourAnchorNgBootstrapDirective implements OnInit, OnDestroy, TourAnchorDirective {


I originally had the `<tour-step-template></tour-step-template>` in app.component.html but it didn't work so that's when I moved it to my child component.

To make sure that I wasn't insane, I created a new test project based on NG13 and installed  `ngx-ui-tour-ng-bootstrap' .  Again it DID NOT install `ngx-ui-tour-core` so I installed it manually.  I also installed all the other _required_ dependencies that weren't installed.  After all this it still presents me with the above error.

In the NPM page for `ngx-ui-tour` it lists the version compatibility for Angular version 12 and 13 as `ngx-ui-tour` version 8.  However, when installing `ngx-ui-tour-ng-bootstrap` version 8 I get the following message

    ngx-ui-tour-ng-bootstrap@8.1.0 requires a peer of @angular/common@>=9.0.0 <13.0.0

This says the version 8 require LESS than NG version 13.  So, which is correct, the NPM page or the npm install output and is this what's causing my error?

**Comment by hakimio** [comment]
Ok, the issue is that you are using really old version of `ngx-ui-tour-ng-bootstrap`. I forgot that `ngx-ui-tour-ng-bootstrap` doesn't follow the same versioning like the rest of the packages since its development started much earlier than the rest. For use with Angular v13, you should install version `10.1.2`.
I'll update the docs to prevent this kind of issue in the future.

**Comment by buddyackerman** [comment]
I got it working using version 10 but I have one more question.  The popups don't have the pointer on the popup like they do in the demo.  Is that some custom styling?  I don't see a way to pass and custom CSS classes to the tour service.

![image](https://user-images.githubusercontent.com/8039125/191086224-557c5bf7-4d4d-48ee-bb2a-2de672cc567a.png)

**Comment by hakimio** [comment]
You have to either include the bootstrap CSS like [indicated in the installation guide](https://hakimio.github.io/ngx-ui-tour/ng-bootstrap/Setup#installation) or if you just want the popover CSS, you can include [bootstrap-popover.scss](https://github.com/hakimio/ngx-ui-tour/blob/master/src/bootstrap-popover.scss) from the demo project.

**Comment by buddyackerman** [comment]
I did include the bootstrap CSS (it really doesn't work without it) and I added the boostrap-popover.scss from the demo as suggested and it's still not showing an arrow.  Do I have to use the custom template in the demo also?

**Comment by hakimio** [comment]
You can try slightly older version of the [bootstrap-popover.scss](https://github.com/hakimio/ngx-ui-tour/blob/master/src/bootstrap-popover.scss). If it still doesn't show up, you'll have to inspect the arrow html element to see what CSS classes it needs.

**Comment by buddyackerman** [comment]
I looked into the DOM elements and the stylesheet and noticed that the bootstrap-popover.scss used the class `popover-arrow` but the class used in the popover is 'arrow'.  Once I modified the stylesheet to use the class `arrow` it works except for when you the step placement is set to bottom, it won't put an arrow pointing up.

**Comment by hakimio** [comment]
You are using older version of `ng-bootstrap` and `ng-popover`. That's why you need [this older CSS](https://github.com/hakimio/ngx-ui-tour/blob/a9d92fad5862f14091e1a71f96d7ab7c2808f5ac/src/bootstrap-popover.scss).
