### ISSUE TITLE
The nextOnAnchorClick in step configuration is not working

### ISSUE THREAD

**Issue by xmarekx** [hakimio/ngx-ui-tour#75]
According to the documentation on the [page](https://hakimio.github.io/ngx-ui-tour/md-menu/API) the property nextOnAnchorClick should  enable/disable to go to the next step when the anchor is clicked. However it doesn't work for NGX-UI-TOUR-MD-MENU and even if it's turned on (true) it still does not allow to proceed to the next step. Wha's more when I create object of type IStepOption the property is unknown.

the second topic is that the placement property also is broken and doesn't work

Looking forward to fast resolution of these problems

**Comment by hakimio** [comment]
What version do you use?

**Comment by xmarekx** [comment]
> What version do you use?

I use Angular 10 and the ngx-ui-tour-md-menu in version 7.0.2

**Comment by hakimio** [comment]
That's a quite old version. The config was introduced in `v8.1` where it was called `goToNextOnAnchorClick`. In `v9` it was renamed to `nextOnAnchorClick`.

**Comment by xmarekx** [comment]
But according to documentation this is version with is compatible with my angular project
![image](https://user-images.githubusercontent.com/57464058/194921075-8e6022b7-f545-45b1-9893-d6b7241ac0bf.png)

**Comment by xmarekx** [comment]
So what should I do?

**Comment by xmarekx** [comment]
> That's a quite old version. The config was introduced in `v8.1` where it was called `goToNextOnAnchorClick`. In `v9` it was renamed to `nextOnAnchorClick`.

But according to documentation this is version with is compatible with my angular project
![image](https://user-images.githubusercontent.com/57464058/194921210-4d9e26db-128e-46af-a44f-8ff0e2f5e8ca.png)

So what should I do?

**Comment by hakimio** [comment]
If you want this feature, you'll have to upgrade your project.

**Comment by hakimio** [comment]
No.

**Comment by xmarekx** [comment]
So is there a way to access the a way to somehow access tour anchor through TS and HTML files?

**Comment by xmarekx** [comment]
And what about placement property?

**Comment by xmarekx** [comment]
And what about placement attribute? it looks like the yPosition has no effect.

**Comment by hakimio** [comment]
Positioning is handled by [Angular Material Menu](https://material.angular.io/components/menu/api#MatMenu) component. If `yPosition` doesn't change for you, most likely that's because you don't have enough space to display it on that side.
If that's not the case, create a demo reproducing the issue on StackBlitz.
