### ISSUE TITLE
When user presses back button on the browser - backdrop still exists however tooltip isn't shown

### ISSUE THREAD

**Issue by mivanyna** [hakimio/ngx-ui-tour#77]
When steps have `route` set and the user presses the browser's back button - the backdrop still exists but no tooltip is shown.

As result:
User can't stop the tour and no tooltip is shown. But interaction with the page is disabled by the backdrop.

Can the prev step be shown if prev step route is active?

Should there be some warning message if you want to exit the tour in this case?

**Comment by hakimio** [comment]
Not sure if it's more sensible to try to guess which step should be selected or to just end the tour. I am leaning towards just ending the tour since there might no longer be an anchor element or the step might require pressing UI element which might cause issues when pressed multiple times.

**Comment by mivanyna** [comment]
> Btw, a similar issue is when no backdrop is shown and fragment is changed - tooltip disappears, but tourService status - `on`
What do you think if adding a check into `setCurrentStep` function to only hide the step if url is not active or anchor isn't available:
```
private setCurrentStep(step: T): void {
        this.currentStep = step;
        this.showStep(this.currentStep);
        this.router.events
            .pipe(filter(event => event instanceof NavigationStart), first())
            .subscribe(() => {
                if (this.currentStep && this.currentStep.hasOwnProperty('route') && (!this.isActiveRoute(step) || !this.anchors[step.anchorId])) {
                    this.hideStep(this.currentStep);
                }
            });
    }

private isActiveRoute(step: T) {
        if (!step.route) {
            return true
        }

        const url = typeof step.route === 'string' ? step.route : this.router.createUrlTree(step.route),
          matchOptions: IsActiveMatchOptions = {
              paths: 'exact',
              matrixParams: 'exact',
              queryParams: 'subset',
              fragment: 'ignored'
          };

        return this.router.isActive(url, matchOptions);
    }
```

**Comment by hakimio** [comment]
Not sure what you are trying to achieve here.
Anyway, I have decided to just end the tour if user navigates to a different page.
You can use [route guard](https://angular.io/api/router/CanDeactivate) to prevent user from being able to navigate to a different page when tour is active.

**Comment by mivanyna** [comment]
Example: Tooltip is shown on the left menu and the user switches tabs on the right side (fragment only changes in url - someUrl#tab1 => someUrl#tab2)

**Comment by hakimio** [comment]
Ok, I think I understand what's the problem. It shouldn't even start listening to `NavigationStart` event if it didn't navigate anywhere (`isRouteActive == true`).

**Comment by mivanyna** [comment]
One more thing I noticed is that there are subscriptions to `this.router.events` in `setCurrentStep` and no unsubscribe.
It seems that with time and going back and forward between steps may cause lots of subscriptions that would be attached and stay there forever. Even when the tour is finished.

**Comment by hakimio** [comment]
It's using `first()` operator to unsubscribe after the first emition.
