### ISSUE TITLE
Backdrop overflows tourAnchor element if it's resized when page not scrollable

### ISSUE THREAD

**Issue by mivanyna** [hakimio/ngx-ui-tour#79]
Setup:
- Show backdrop
- Set page not scrollable

I have two scenarios when backdrop isn't placed well:
1. If I want to add border 2px for class `.touranchor--is-active` to highlight the element - bottom backdrop class overflows the element
2. If my tourAnchor change size (for example menu that can be collapsed/expanded) backdrop is not updated

It would be great if we can track element resize and update backdrop position.
Seems that page resize isn't triggered in this case.

![image](https://user-images.githubusercontent.com/10868397/201389444-7507448f-fd22-4579-96b1-4d044e15df8e.png)

**Comment by mivanyna** [comment]
Hi, @hakimio.
Have added a PR on how it can be fixed, what do you think?
https://github.com/hakimio/ngx-ui-tour/pull/80

**Comment by hakimio** [comment]
@mivanyna I think your use of `ResizeObserver` would break SSR apps, debouncing might be necessary to avoid calling `setBackdropPosition()` too often and it might be a good idea to only call `setBackdropPosition()` once when both window and the target element resizes. Might be a good idea to wrap `ResizeObserver` usage with an rxjs Observable to be able to use rxjs operators.

**Comment by mivanyna** [comment]
@hakimio,  please feel free to apply the necessary changes.
Otherwise, I'll take a look tomorrow maybe or in monday.

**Comment by hakimio** [comment]
No rush. Do it whenever it's convenient for you.

**Comment by mivanyna** [comment]
How do you add new dependencies to the project?

**Comment by mivanyna** [comment]
Btw, that library uses the same `ResizeObserver`, one difference is it run callback using zone:
```
observer = new ResizeObserver(entries => {
                ngZone.run(() => {
                    subscriber.next(entries);
                });
            });
```
  https://github.com/ng-web-apis/resize-observer/blob/master/projects/resize-observer/src/services/resize-observer.service.ts

And fails to install, I assume because of angular version 12

**Comment by hakimio** [comment]
Yes, it still uses ResizeObserver but [it checks if it is supported](https://github.com/ng-web-apis/resize-observer/blob/master/projects/resize-observer/src/services/resize-observer.service.ts#L19) to avoid breaking SSR apps.
Anyway, it's meant to be used inside components because it's injecting `ElementRef`. In our case we want to use it in another service, so it might be best if we would just implement our own version of the service.

> And fails to install, I assume because of angular version 12

It accepts [any Angular version >= 12](https://github.com/ng-web-apis/resize-observer/blob/master/projects/resize-observer/package.json#L24).

**Comment by hakimio** [comment]
@mivanyna I have released a new version. See if it works as you wanted.

**Comment by mivanyna** [comment]
Thank you very much! Will check!

**Comment by hakimio** [comment]
Remember to star the project if you like it ;)
