### ISSUE TITLE
Automatic page scroll on page resize

### ISSUE THREAD

**Issue by directcuteo** [hakimio/ngx-ui-tour#8]
### Current behavior
Page is not scrolling to focus on the currently highlighted element if the element is repositioned due to window resizing.

### Expected behavior
If an element is repositioned due to window resizing and the element is focused by Ui Tour, the page should scroll to keep the focused element in the user view.

Thank you!

**Comment by hakimio** [comment]
@directcuteo I have released a new version with this feature. Check it out to see if it works as you wanted.
