### ISSUE TITLE
Build error with ngx-ui-tour-md-menu - When triggering Angular build (v14) throwing error

### ISSUE THREAD

**Issue by appaiya** [hakimio/ngx-ui-tour#82]
After the update of 'ngx-ui-tour-md-menu' to v9.2.0 getting build error.

My project is on Angular 14.

"@angular/material": "^14.2.7",
"@angular/core": "^14.2.10",
"@angular/common": "^14.2.10",
"typescript": "^4.6.2"
"@angular/cdk": "^14.2.7",

and 

"ngx-ui-tour-md-menu": "^9.2.0",

Find the screenshot of error below.

![image](https://user-images.githubusercontent.com/53377064/203254416-36df366f-a5db-4bca-9f6d-94758dea7162.png)

**Comment by hakimio** [comment]
@cpotemski take a look at this.

**Comment by appaiya** [comment]
@hakimio Thanks, works fine now.
