### ISSUE TITLE
Rxjs v6 build error after updating to v9.3.0

### ISSUE THREAD

**Issue by appaiya** [hakimio/ngx-ui-tour#83]
After the update of 'ngx-ui-tour-md-menu' to v9.3.0 getting build error.

My project is on Angular 14.

"@angular/material": "^14.2.7",
"@angular/core": "^14.2.10",
"@angular/common": "^14.2.10",
"typescript": "^4.6.2"
"@angular/cdk": "^14.2.7",

and

"ngx-ui-tour-md-menu": "^9.3.0",

Find the screenshot of error below.

![Screenshot 2022-11-23 203540](https://user-images.githubusercontent.com/53377064/203579908-5f830a61-aeed-4715-98c1-38699ac45e92.png)

**Comment by hakimio** [comment]
You either have to upgrade your rxjs version to v7 or keep using v9.2.1 for now.

**Comment by hakimio** [comment]
I think I'll fix this for v9, but starting from v10, we'll be dropping rxjs v6 support.
