### ISSUE TITLE
[ng-bootstrap] Tooltip doesn't show up when two consequent steps have the same anchor id

### ISSUE THREAD

**Issue by mivanyna** [hakimio/ngx-ui-tour#84]
I have a wizard where I want the user to press the Next button a few times.
My 2 or more steps have the same tourAnchor. After 1st tooltip is shown - the next one will not pop up.

As example just add one more step in `ng-bootstrap.component.ts` to the `tourSteps` like: 
```
     ...
     {
        anchorId: 'installation', // existing
        content: 'First, install the library...',
        title: 'Installation',
        route: 'ng-bootstrap/Setup'
    },
    {
        anchorId: 'installation', //new one
        content: 'Second tooltip info...',
        title: 'Installation 2nd tooltip',
        route: 'ng-bootstrap/Setup'
    },
   ...
```

**Comment by hakimio** [comment]
I don't see anything wrong on `ngx-ui-tour` side and this scenario works fine when using material design UI implementation. I'd say it's an upstream issue - popover doesn't show up after fast open/close toggling, but I don't have time to investigate it more now. If you can find a simple fix on this library side, feel free to open a PR.

**Comment by hakimio** [comment]
Also, it works with `ngx-bootstrap` implementation which is implemented the same way.

**Comment by hakimio** [comment]
Ok, I think I found a work-around.
Try out the attached version and let me know if it fixes the issue for you.
[ngx-ui-tour-ng-bootstrap.zip](https://github.com/hakimio/ngx-ui-tour/files/10091818/ngx-ui-tour-ng-bootstrap.zip)

**Comment by hakimio** [comment]
Released `v11.3.2` on npm.

**Comment by mivanyna** [comment]
Wow, that was quick, thank you!
Will check later today!
I like how you make the lib better and better!

**Comment by mivanyna** [comment]
Btw, have found a workaround - `[animation]="false"` for anchor directive in html also fixes the issue.

**Comment by hakimio** [comment]
I know but this fix should allow you to use animations.

**Comment by mivanyna** [comment]
Yeah, this one is definitely better!
