### ISSUE TITLE
Make stepId: string | number

### ISSUE THREAD

**Issue by mivanyna** [hakimio/ngx-ui-tour#86]
In this case, I can use an enum as stepId and not strings

**Comment by hakimio** [comment]
Feel free to make a PR for this.

**Comment by mivanyna** [comment]
As I see there is refactoring needed for `loadStep`(which has logic based on type of input: number means index, string - stepId) and `startAt` functions.
This will impact users who use `startAt` function.
Is it ok to have `startAtIndex` and `startAtStepId` functions instead?
Or what would be your suggestions?

**Comment by hakimio** [comment]
That's not a simple refactoring but a breaking change. We can do this for the next major version (`v10`).

**Comment by hakimio** [comment]
After looking into this a bit more, I decided not to proceed with the feature since it introduces a lot of breaking changes for very little gain.
You can still assign `stepId` to an enum if enum values are strings:
```ts
enum MySteps {
    Step1 = 'Step1',
    Step2 = 'Step2',
    Step3 = 'Step3'
}
```
