### ISSUE TITLE
ngx-ui-tour-ng-bootstrap not blocking base web

### ISSUE THREAD

**Issue by beuwolf-u** [hakimio/ngx-ui-tour#9]
When the tour starts on, using the ng-bootstrap it allows to click or do action with the site that should be blocked, it happen even if the enableBackdrop is on.

https://user-images.githubusercontent.com/59735140/114889816-71a3f780-9dd8-11eb-97f9-1b8200af7e47.mov

**Comment by hakimio** [comment]
Check out [How to disable main content scrolling when UI tour is active?](https://github.com/hakimio/ngx-ui-tour#how-to-disable-main-content-scrolling-when-ui-tour-is-active) FAQ. You can use the same principle to disable pointer events on your main content:
```css
.no-scroll {
    overflow: hidden;
    pointer-events: none;
}
```

**Comment by hakimio** [comment]
Should it just work the same like "md-menu", where clicking on the overlay closes it?

**Comment by beuwolf-u** [comment]
Yeah it should had the same behavior, or just not allow it, because if u do a miss click it would have to start all over again

**Comment by hakimio** [comment]
Ok, I will look into it sometime next week.

**Comment by hakimio** [comment]
@beuwolf-u Now it will block base web page interaction when backdrop is enabled. Try the new version and let me know if it works as intended.

**Comment by beuwolf-u** [comment]
![image](https://user-images.githubusercontent.com/59735140/115409516-d1771580-a1bf-11eb-9ae0-c4bd9a794043.png)
