### ISSUE TITLE
Tour widget with backdrop is blocking anchor element on (actual) mobile device

### ISSUE THREAD

**Issue by gabekarkanis** [hakimio/ngx-ui-tour#90]
The tour widget popup selector is blocking elements on mobile device. It works perfect in regular web mode and even in the web mobile simulator. However, when I test on the actual device (not the simulator) the positioning isn't right (particularly in landscape mode when scrolling up or down, but also in portrait). I can't figure out the exact steps to reproduce, but it seems scrolling makes it worse. And if I zoom in/out the browser on my device a few times it seems to fix it.

Angular version: 13.3.0
NGX UI Tour (ngx-ui-tour-md-menu) version: 8.1.2

![IMG_6918](https://user-images.githubusercontent.com/2388228/206559043-33d7b4c4-f0cb-4b2d-af7c-55383a6cc4d2.PNG)

**Comment by hakimio** [comment]
Positioning is handled by [mat-menu](https://material.angular.io/components/menu/overview) when you use `ngx-ui-tour-md-menu`. Not much this library can do to fix this.
Anyway, have you tried `disablePageScrolling` [step config](https://hakimio.github.io/ngx-ui-tour/md-menu/API#step-config) which prevents the user from being able to scroll while the tour is active?

**Comment by gabekarkanis** [comment]
Using `disablePageScrolling` works surprisingly well at resolving the issue. Initially I didn't think to use it, but it ended up working quite nicely. Thank you for the help and quick response!

**Comment by hakimio** [comment]
You are welcome. Remember to star the library if you like it :)

**Comment by gabekarkanis** [comment]
Starred 👍🏼

I may have spoke a bit too soon. It definitely fixed the issue for portrait mode. I think where the issues are persisting is when in landscape mode and there is very small vertical height to work with. Essentially the browser bar is forced open on `disablePageScrolling` and in landscape leaves hardly any wiggle room for the tour widget and that's when the odd clipping and jittering behaviour starts when the tour is highlighting elements at the bottom of the page.

On the bright side it's less common for users to be in landscape and get to the very bottom of the responsive page in the tour so those are positives.

**Comment by hakimio** [comment]
Closing since this library doesn't control `mat-menu` positioning and can't fix it.
