### ISSUE TITLE
Remove "Prev" button if there's no previous step

### ISSUE THREAD

**Issue by PeterSR** [hakimio/ngx-ui-tour#93]
Is it possible to add option to remove the "Prev" button, if there's no previous step?

Currently, it is disabled, but it would be nice if there was a way to remove it entirely.

It could be a global setting or part of the step configuration. 

I have tried setting the `prevBtnTitle` to a blank string in the hope that it would disappear altogether, but the arrow is still there.

---

Using `ngx-ui-tour-md-menu` and Angular 14.

**Comment by hakimio** [comment]
There are no plans to add an option like that. You can customize the step template instead: https://hakimio.github.io/ngx-ui-tour/md-menu/Misc#custom-template

**Comment by PeterSR** [comment]
Fair enough. And thank you for pointing me in that direction.
