### ISSUE TITLE
Introduce `nonUniqueAnchorHandling` step option

### ISSUE THREAD

**Issue by miaucl** [hakimio/ngx-ui-tour#96]
This is a proposition for a fail-safe handling of multiple same anchors. I have an example where I try to explain how my inbox works and therefore I need to reference **one** of the posts in the inbox (preferably the first one^^), and therefore I just added the same anchor to all my posts. This works fine and even tough there is multiple times the same anchor, only the first gets picked and my tour works fine. **But**, I get an error message in the logs which complains about multiple registrations of the same anchor (obviously).

```
ERROR Error: anchorId inbox-intro.archive-message already registered!
```

Might it be possible to add a flag to control this behavior step by step, let's say: `unique` (default and same as now) | `first` (take first registration) | `last` (overwrite registrations)

Or does this conflict with the functioning of the library? 

I can add logic on my side to ensure adding it only once or just cope with the errors'', but it would be a lot easier to control that.

**Comment by hakimio** [comment]
I understand that it's a common issue and something should be done about it. Maybe we could introduce a step option like `nonUniqueAnchorHandling: 'error' | 'registerFirst' | 'registerLast'` in the next version.
Anyway, right now you can have similar functionality by using empty anchor which will be ignored:
```html
<div
	*ngFor="let item of items; let isFirst = first"
	[tourAnchor]="isFirst ? 'some.anchor.id' : ''"
>
	{{item}}
</div>
```

**Comment by miaucl** [comment]
Thanks, I like that. This is what I do currently 👍

**Comment by mivanyna** [comment]
Another workaround is: 
<div
	*ngFor="let item of items; let index = index"
	tourAnchor="some.anchor.id_{{index}}"
>
	{{item}}
</div>

**Comment by hakimio** [comment]
Option `duplicateAnchorHandling` has been added in the `v10` release. Check out [release announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v10.0.0) for more info.
