### ISSUE TITLE
Add ability to configurable space between the anchor element and backdrop

### ISSUE THREAD

**Issue by mivanyna** [hakimio/ngx-ui-tour#98]
Would be good to have some configurable space between the anchor element and backdrop(between border and backdrop in this case):
image
![image](https://user-images.githubusercontent.com/10868397/209308059-7dbae3be-c90a-4e1b-884d-635335f1af8a.png)

As an example, I have a button with rounded corners and there are white spaces in the corners between the backdrop and button corners or in case I want to highlight the first row value with the column header in the table.

**Comment by hakimio** [comment]
I thought a little bit about this. Adding padding to the backdrop is easy but then tour step UI will look like it's positioned incorrectly and adjusting tour step position is a lot more tricky since it's positioned by 3rd party library. As a result, I don't plan to proceed with this feature but if you can come up with some clever way to adjust tour step position when padding is applied to the backdrop, feel free to create a PR demonstrating you solution.

**Comment by mivanyna** [comment]
Hi, we have a very "interesting" time in Ukraine, don't have time to check how it can be done right now.
But maybe will check later this week.

**Comment by hakimio** [comment]
@mivanyna 
Hope the situation in Ukraine will improve this year. Stay safe.

**Comment by hakimio** [comment]
@mivanyna Here is a simple idea how you can add extra padding right now to some "display: block" div containers. It should be possible with some simple CSS:
```css
.touranchor--is-active {
    padding: 16px;
    margin: -16px;
}
```

**Comment by hakimio** [comment]
[Here](https://stackblitz.com/edit/angular-wau2z8?file=src%2Fapp%2Fui-tour-demo.component.html,src%2Fapp%2Fui-tour-demo.component.ts) is a small demo showing this approach in action.

**Comment by mivanyna** [comment]
@hakimio yeah, but that doesn't work for cases I described above:
>As an example, I have a button with rounded corners and there are white spaces in the corners between the backdrop and button corners or in case I want to highlight the first row value with the column header in the table.
![image](https://user-images.githubusercontent.com/10868397/215089976-1a4c2bf5-b3fc-4b40-879f-6dfd192d0e9f.png)

**Comment by hakimio** [comment]
You can add the button in a div container and apply the styling to that container. Anyway, I know that it's not ideal but I don't have a better solution/workaround right now.

**Comment by mivanyna** [comment]
Thanks!

**Comment by mivanyna** [comment]
Hi @hakimio, here is a PR with implementation for NG Boostrap, please take a look and let me know your thoughts
https://github.com/hakimio/ngx-ui-tour/pull/118
